const LS='myTravel_v2', CFG='myTravel_supabase';
const seed={rate:.22,expenses:[],trips:[
{id:'miyako2026',name:'宮古島',emoji:'🌴',start:'2026-11-11',end:'2026-11-14',theme:'悠閒自駕＋海景＋咖啡廳',center:[24.8055,125.2811],flights:[{dir:'去程',date:'2026-11-11',route:'台灣 → 宮古島',time:'約 13:00 抵達'},{dir:'回程',date:'2026-11-14',route:'宮古島 → 台灣',time:'約 14:00 起飛'}],hotels:[{name:'Watermark Hotel & Resorts Okinawa Miyakojima',from:'2026-11-11',to:'2026-11-14',note:'3 晚'}],itinerary:{'2026-11-11':[{id:'m1',time:'13:00',title:'抵達宮古島',type:'交通',note:'取行李、辦理租車',lat:24.7828,lng:125.2951},{id:'m2',time:'14:00',title:'租車取車',type:'交通',note:'確認保險、油種、還車方式',lat:24.7828,lng:125.2951},{id:'m3',time:'15:30',title:'飯店 Check-in',type:'住宿',note:'Watermark Hotel',lat:24.827,lng:125.138},{id:'m4',time:'18:30',title:'宮古牛燒肉',type:'餐廳',note:'晚餐店家可再補',lat:24.8055,lng:125.2811}],'2026-11-12':[{id:'m5',time:'10:00',title:'伊良部大橋',type:'景點',note:'悠閒自駕看海',lat:24.8108,lng:125.214},{id:'m6',time:'11:00',title:'牧山展望台',type:'景點',note:'看伊良部大橋',lat:24.837,lng:125.1926},{id:'m7',time:'13:30',title:'17END',type:'景點',note:'依天氣彈性停留',lat:24.826,lng:125.13},{id:'m8',time:'16:00',title:'咖啡廳時間',type:'餐廳',note:'不趕行程',lat:24.8267,lng:125.1758}],'2026-11-13':[{id:'m9',time:'10:00',title:'與那霸前濱海灘',type:'景點',note:'散步看海',lat:24.7354,lng:125.2635},{id:'m10',time:'11:30',title:'來間大橋',type:'景點',note:'自駕過橋',lat:24.7282,lng:125.257},{id:'m11',time:'12:00',title:'龍宮城展望台',type:'景點',note:'俯瞰海景',lat:24.724,lng:125.2503},{id:'m12',time:'14:00',title:'咖啡廳',type:'餐廳',note:'下午留白',lat:24.725,lng:125.247}],'2026-11-14':[{id:'m13',time:'09:00',title:'早餐／附近散步',type:'景點',note:'最後一天不排遠',lat:24.827,lng:125.138},{id:'m14',time:'11:00',title:'加油／還車',type:'交通',note:'預留接駁時間',lat:24.7828,lng:125.2951},{id:'m15',time:'14:00',title:'宮古島起飛回台灣',type:'交通',note:'提早到機場',lat:24.7828,lng:125.2951}]},checks:[{id:'mc1',name:'確認護照效期',done:false},{id:'mc2',name:'預約宮古島租車',done:false},{id:'mc3',name:'準備台灣駕照＋日文譯本',done:false},{id:'mc4',name:'確認旅遊保險',done:false},{id:'mc5',name:'準備 eSIM／網卡',done:false}],shops:[{id:'ms1',name:'雪鹽／宮古島伴手禮',done:false},{id:'ms2',name:'沖繩限定零食',done:false}]},
{id:'hokkaido2027',name:'北海道',emoji:'⛷️',start:'2027-02-18',end:'2027-03-05',theme:'札幌採買＋近郊滑雪＋二世古',center:[43.0618,141.3545],flights:[{dir:'去程',date:'2027-02-18',route:'台灣 → 北海道',time:'待填'},{dir:'回程',date:'2027-03-05',route:'北海道 → 台灣',time:'待填'}],hotels:[{name:'札幌住宿',from:'2027-02-18',to:'2027-02-24',note:'待補實際飯店'},{name:'Lodge Koropokkuru',from:'2027-02-24',to:'2027-02-28',note:'已預訂'}],itinerary:{'2027-02-18':[{id:'h1',time:'15:00',title:'抵達札幌／Check-in',type:'交通',note:'先放行李',lat:43.0618,lng:141.3545}],'2027-02-19':[{id:'h2',time:'10:30',title:'札幌雪具店採買',type:'購物',note:'雪板／固定器／雪鞋',lat:43.0618,lng:141.3545}],'2027-02-20':[{id:'h3',time:'08:00',title:'札幌近郊滑雪',type:'滑雪',note:'依雪況決定',lat:43.072,lng:141.0825}],'2027-02-21':[],'2027-02-22':[],'2027-02-23':[],'2027-02-24':[{id:'h6',time:'09:00',title:'札幌 → 二世古',type:'交通',note:'朋友會合',lat:42.8048,lng:140.6874},{id:'h7',time:'15:00',title:'Lodge Koropokkuru Check-in',type:'住宿',note:'已預訂',lat:42.8635,lng:140.704}],'2027-02-25':[{id:'h8',time:'08:30',title:'二世古滑雪',type:'滑雪',note:'Annupuri / Hirafu / Village',lat:42.8487,lng:140.6488}],'2027-02-26':[],'2027-02-27':[],'2027-02-28':[],'2027-03-01':[],'2027-03-02':[],'2027-03-03':[],'2027-03-04':[],'2027-03-05':[]},checks:[{id:'hc1',name:'確認護照效期',done:false},{id:'hc2',name:'確認航班與行李額度',done:false},{id:'hc3',name:'預約札幌 → 二世古交通',done:false},{id:'hc4',name:'確認滑雪／特殊運動保險',done:false}],shops:[{id:'hs1',name:'雪具／裝備',done:false},{id:'hs2',name:'北海道伴手禮',done:false}]}
]};
const recs={miyako2026:[{name:'砂山海灘',note:'市區北側人氣海灘',lat:24.8436,lng:125.2782},{name:'島之驛宮古',note:'伴手禮與簡單餐飲',lat:24.7934,lng:125.2938},{name:'通池',note:'伊良部島自然景觀',lat:24.8427,lng:125.117}],hokkaido2027:[{name:'大通公園',note:'札幌市中心散步',lat:43.0605,lng:141.3475},{name:'狸小路商店街',note:'藥妝與採買',lat:43.057,lng:141.3512},{name:'Niseko Annupuri',note:'二世古主力雪場',lat:42.8487,lng:140.6488}]};
function clone(x){return JSON.parse(JSON.stringify(x))}
function range(a,b){let r=[],d=new Date(a+'T00:00:00'),e=new Date(b+'T00:00:00');while(d<=e){r.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return r}
function normalize(s){if(!s||!Array.isArray(s.trips)||!s.trips.length)s=clone(seed);if(!Array.isArray(s.expenses))s.expenses=[];if(typeof s.rate!=='number')s.rate=.22;s.trips.forEach(t=>{t.itinerary=t.itinerary||{};range(t.start,t.end).forEach(d=>t.itinerary[d]??=[]);t.checks=t.checks||[];t.shops=t.shops||[];t.flights=t.flights||[];t.hotels=t.hotels||[];t.center=t.center||[35.6762,139.6503]});return s}
let state=normalize(JSON.parse(localStorage.getItem(LS)||'null')),curTrip=state.trips[0].id,curDate=state.trips[0].start,map,bigMap,markers=[],bigMarkers=[],sb=null,lastCloudUpdatedAt=null,isPulling=false;
const $=id=>document.getElementById(id);
const trip=()=>state.trips.find(t=>t.id===curTrip)||state.trips[0];
const save=()=>{state._updatedAt=new Date().toISOString();localStorage.setItem(LS,JSON.stringify(state));renderAll();if(sb)pushCloud()};
function fmt(d){let x=new Date(d+'T00:00:00');return `${x.getMonth()+1}/${x.getDate()}（${'日一二三四五六'[x.getDay()]}）`}
function fmtTime(v){if(!v)return '尚未同步';let d=new Date(v);if(Number.isNaN(d.getTime()))return '尚未同步';return d.toLocaleString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}
function updateCloudNote(text='雲端同步已啟用。'){let n=$('cloudNote');if(!n)return;n.className='note good';n.innerHTML=`${text}<br><span style="font-size:12px">最後更新：${fmtTime(lastCloudUpdatedAt||state._updatedAt)}</span>`}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('pageTitle').textContent={home:'我的旅行',itinerary:'行程',mapPage:'旅行地圖',money:'旅行記帳',more:'更多'}[id];if(id==='mapPage')setTimeout(renderBigMap,50);if(id==='itinerary')setTimeout(()=>map?.invalidateSize(),50)}
function renderHome(){const now=new Date();now.setHours(0,0,0,0);let u=[...state.trips].sort((a,b)=>a.start.localeCompare(b.start)).find(t=>new Date(t.end+'T23:59:59')>=now)||state.trips[0];$('nextTripName').textContent=`${u.emoji||'✈️'} ${u.name}`;$('nextTripDates').textContent=`${u.start} ～ ${u.end} · ${u.theme||''}`;$('daysLeft').textContent=Math.max(0,Math.ceil((new Date(u.start+'T00:00:00')-now)/86400000));let c=$('tripCards');c.innerHTML='';state.trips.forEach(t=>{let d=document.createElement('div');d.className='tripcard';d.innerHTML=`<span class="pill">${range(t.start,t.end).length} DAYS</span><h3>${t.emoji||'✈️'} ${t.name}</h3><div class="muted">${t.start} ～ ${t.end}</div><p>${t.theme||''}</p><div class="row"><button class="btn" onclick="openTrip('${t.id}')">打開旅行</button><button class="btn alt" onclick="openTripEditor('${t.id}')">編輯</button><button class="btn red" onclick="deleteTrip('${t.id}')">刪除</button></div>`;c.appendChild(d)});let add=document.createElement('button');add.className='addtrip';add.innerHTML='<b>＋ 新增旅行</b><span>建立下一趟旅程</span>';add.onclick=()=>openTripEditor();c.appendChild(add)}
function syncSelects(){['tripSelect','mapTripSelect','checkTripSelect','shopTripSelect'].forEach(id=>{let e=$(id);e.innerHTML=state.trips.map(t=>`<option value="${t.id}">${t.emoji||'✈️'} ${t.name}</option>`).join('');e.value=curTrip})}
function openTrip(id){curTrip=id;curDate=trip().start;syncSelects();renderItinerary();renderMore();showPage('itinerary')}
function initMaps(){map=L.map('map').setView(trip().center,10);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);bigMap=L.map('bigMap').setView(trip().center,8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(bigMap)}
function renderItinerary(){let t=trip();$('tripTitle').textContent=`${t.emoji||'✈️'} ${t.name}`;$('tripRange').textContent=`${t.start} ～ ${t.end} · ${t.theme||''}`;$('dayTabs').innerHTML=range(t.start,t.end).map(d=>`<button class="tab ${d===curDate?'active':''}" onclick="curDate='${d}';renderItinerary()">${fmt(d)}</button>`).join('');$('dayTitle').textContent=fmt(curDate);let arr=t.itinerary[curDate]||[];$('timeline').innerHTML=arr.length?arr.map(i=>`<div class="item"><div class="time">${i.time||'—'}</div><div><div class="title">${i.title}</div><div class="meta">${i.type}${i.note?' · '+i.note:''}</div></div><button class="btn sm red" onclick="delItem('${i.id}')">刪</button></div>`).join(''):'<div class="empty">這天還沒有行程</div>';$('recGrid').innerHTML=(recs[t.id]||[]).map(r=>`<div class="rec"><b>${r.name}</b><div class="muted">${r.note}</div><button class="btn sm" onclick='addRec(${JSON.stringify(r)})'>＋加入</button></div>`).join('');renderMap()}
function renderMap(){markers.forEach(m=>map.removeLayer(m));markers=[];(trip().itinerary[curDate]||[]).filter(x=>x.lat&&x.lng).forEach(i=>markers.push(L.marker([i.lat,i.lng]).addTo(map).bindPopup(i.title)));if(markers.length)map.fitBounds(L.featureGroup(markers).getBounds().pad(.2));else map.setView(trip().center,10)}
function renderBigMap(){bigMarkers.forEach(m=>bigMap.removeLayer(m));bigMarkers=[];Object.values(trip().itinerary).flat().filter(x=>x.lat&&x.lng).forEach(i=>bigMarkers.push(L.marker([i.lat,i.lng]).addTo(bigMap).bindPopup(i.title)));if(bigMarkers.length)bigMap.fitBounds(L.featureGroup(bigMarkers).getBounds().pad(.15));else bigMap.setView(trip().center,8);bigMap.invalidateSize()}
function toggleAdd(v){$('addBox').style.display=v?'block':'none'}
function addItem(){let title=$('iTitle').value.trim();if(!title)return alert('請輸入名稱');trip().itinerary[curDate].push({id:crypto.randomUUID(),time:$('iTime').value,title,type:$('iType').value,note:$('iNote').value.trim(),lat:parseFloat($('iLat').value)||null,lng:parseFloat($('iLng').value)||null});['iTitle','iNote','iLat','iLng'].forEach(id=>$(id).value='');toggleAdd(false);save()}
function delItem(id){trip().itinerary[curDate]=trip().itinerary[curDate].filter(x=>x.id!==id);save()}
function addRec(r){trip().itinerary[curDate].push({id:crypto.randomUUID(),time:'10:00',title:r.name,type:'景點',note:r.note,lat:r.lat,lng:r.lng});save()}
function renderMoney(){let sum=0;$('expenseRows').innerHTML=state.expenses.map(e=>{sum+=+e.amount;let t=state.trips.find(x=>x.id===e.tripId);return `<tr><td>${t?.name||''}</td><td>${e.date}</td><td>${e.cat}</td><td>${e.name}</td><td>¥${(+e.amount).toLocaleString()}</td><td>NT$${Math.round(e.amount*state.rate).toLocaleString()}</td><td><button class="btn sm red" onclick="delExpense('${e.id}')">刪</button></td></tr>`}).join('');$('sumJPY').textContent='¥'+sum.toLocaleString();$('sumTWD').textContent='NT$'+Math.round(sum*state.rate).toLocaleString();$('sumCount').textContent=state.expenses.length;$('rate').value=state.rate;$('eDate').value=trip().start}
function addExpense(){let n=$('eName').value.trim(),a=parseFloat($('eAmount').value);if(!n||!a)return alert('請輸入名稱與金額');state.expenses.push({id:crypto.randomUUID(),tripId:curTrip,date:$('eDate').value,cat:$('eCat').value,name:n,amount:a});$('eName').value='';$('eAmount').value='';save()}
function delExpense(id){state.expenses=state.expenses.filter(x=>x.id!==id);save()}
function setRate(){state.rate=parseFloat($('rate').value)||.22;save()}
function renderMore(){renderChecks();renderShops();let t=trip();$('bookingInfo').innerHTML='<b>航班</b>'+t.flights.map(f=>`<div class="setting"><b>${f.dir}</b> · ${f.date}<div>${f.route}</div><div class="muted">${f.time}</div></div>`).join('')+'<div style="margin-top:12px"><b>住宿</b></div>'+t.hotels.map(h=>`<div class="setting"><b>${h.name}</b><div>${h.from} ～ ${h.to}</div><div class="muted">${h.note||''}</div></div>`).join('');if(sb)updateCloudNote()}
function renderChecks(){let t=state.trips.find(x=>x.id===$('checkTripSelect').value)||trip();$('checkRows').innerHTML=t.checks.map(i=>`<div class="check ${i.done?'done':''}"><input type="checkbox" ${i.done?'checked':''} onchange="toggleCheck('${t.id}','${i.id}')"><span>${i.name}</span></div>`).join('')}
function addCheck(){let n=$('checkInput').value.trim();if(!n)return;let t=state.trips.find(x=>x.id===$('checkTripSelect').value);t.checks.push({id:crypto.randomUUID(),name:n,done:false});$('checkInput').value='';save()}
function toggleCheck(tid,id){let i=state.trips.find(x=>x.id===tid).checks.find(x=>x.id===id);i.done=!i.done;save()}
function renderShops(){let t=state.trips.find(x=>x.id===$('shopTripSelect').value)||trip();$('shopRows').innerHTML=t.shops.map(i=>`<div class="check ${i.done?'done':''}"><input type="checkbox" ${i.done?'checked':''} onchange="toggleShop('${t.id}','${i.id}')"><span>${i.name}</span></div>`).join('')}
function addShop(){let n=$('shopInput').value.trim();if(!n)return;let t=state.trips.find(x=>x.id===$('shopTripSelect').value);t.shops.push({id:crypto.randomUUID(),name:n,done:false});$('shopInput').value='';save()}
function toggleShop(tid,id){let i=state.trips.find(x=>x.id===tid).shops.find(x=>x.id===id);i.done=!i.done;save()}
function renderAll(){state=normalize(state);syncSelects();renderHome();renderItinerary();renderMoney();renderMore();localStorage.setItem(LS,JSON.stringify(state))}
function openTripEditor(id=''){let t=id?state.trips.find(x=>x.id===id):null;$('tmTitle').textContent=t?'編輯旅行':'新增旅行';$('tmId').value=t?.id||'';$('tmName').value=t?.name||'';$('tmEmoji').value=t?.emoji||'✈️';$('tmStart').value=t?.start||'';$('tmEnd').value=t?.end||'';$('tmTheme').value=t?.theme||'';$('tmHotel').value=t?.hotels?.[0]?.name||'';$('tmOutbound').value=t?.flights?.[0]?.route||'';$('tmInbound').value=t?.flights?.[1]?.route||'';$('tmLat').value=t?.center?.[0]||'';$('tmLng').value=t?.center?.[1]||'';$('tripModal').classList.add('show')}
function closeTripEditor(){$('tripModal').classList.remove('show')}
function saveTrip(){let name=$('tmName').value.trim(),start=$('tmStart').value,end=$('tmEnd').value;if(!name||!start||!end)return alert('請填旅行名稱與日期');if(end<start)return alert('結束日期不能早於開始日期');let id=$('tmId').value,old=id?state.trips.find(x=>x.id===id):null,itin=old?.itinerary||{};range(start,end).forEach(d=>itin[d]??=[]);Object.keys(itin).forEach(d=>{if(d<start||d>end)delete itin[d]});let obj={id:id||('trip_'+Date.now()),name,emoji:$('tmEmoji').value.trim()||'✈️',start,end,theme:$('tmTheme').value.trim(),center:[parseFloat($('tmLat').value)||35.6762,parseFloat($('tmLng').value)||139.6503],flights:[{dir:'去程',date:start,route:$('tmOutbound').value.trim()||'待填',time:'待填'},{dir:'回程',date:end,route:$('tmInbound').value.trim()||'待填',time:'待填'}],hotels:$('tmHotel').value.trim()?[{name:$('tmHotel').value.trim(),from:start,to:end,note:''}]:(old?.hotels||[]),itinerary:itin,checks:old?.checks||[{id:crypto.randomUUID(),name:'確認護照效期',done:false},{id:crypto.randomUUID(),name:'確認航班／交通',done:false},{id:crypto.randomUUID(),name:'確認旅遊保險',done:false},{id:crypto.randomUUID(),name:'準備 eSIM／網卡',done:false}],shops:old?.shops||[]};if(old)Object.assign(old,obj);else state.trips.push(obj);curTrip=obj.id;curDate=obj.start;closeTripEditor();save()}
function deleteTrip(id){if(state.trips.length<=1)return alert('至少保留一趟旅行');let t=state.trips.find(x=>x.id===id);if(!confirm(`確定刪除「${t.name}」？\n這會一起刪除該旅行的行程、清單與相關記帳。`))return;state.trips=state.trips.filter(x=>x.id!==id);state.expenses=state.expenses.filter(x=>x.tripId!==id);if(curTrip===id){curTrip=state.trips[0].id;curDate=state.trips[0].start}save()}
function cloudCfg(){return JSON.parse(localStorage.getItem(CFG)||'null')}
function cloudStatus(t,d=''){$('syncStatus').textContent=t;if(d){$('cloudNote').className='note';$('cloudNote').textContent=d}}
async function applyCloudRow(data,force=false){if(!data?.payload?.trips?.length)return false;let cloudTime=new Date(data.updated_at||data.payload._updatedAt||0).getTime(),localTime=new Date(state._updatedAt||0).getTime();lastCloudUpdatedAt=data.updated_at||data.payload._updatedAt;if(force||cloudTime>localTime){let keepId=curTrip;state=normalize(data.payload);curTrip=state.trips.some(t=>t.id===keepId)?keepId:state.trips[0].id;if(!trip().itinerary[curDate])curDate=trip().start;localStorage.setItem(LS,JSON.stringify(state));renderAll();return true}updateCloudNote();return false}
async function pullLatestCloud(force=false){if(!sb||isPulling)return false;isPulling=true;try{let {data,error}=await sb.from('travel_state').select('*').eq('id','default').maybeSingle();if(error)throw error;let changed=await applyCloudRow(data,force);cloudStatus('已同步');updateCloudNote(changed?'已取得另一台裝置的最新資料。':'雲端同步已啟用。');return changed}catch(e){console.error('auto sync failed',e);cloudStatus('同步失敗',e.message);return false}finally{isPulling=false}}
async function setupCloud(){let c=cloudCfg();$('sbUrl').value=c?.url||'';$('sbKey').value=c?.key||'';if(!c?.url||!c?.key)return cloudStatus('本機模式');try{sb=supabase.createClient(c.url,c.key);let {data,error}=await sb.from('travel_state').select('*').eq('id','default').maybeSingle();if(error)throw error;if(data?.payload?.trips?.length){await applyCloudRow(data,true)}else await pushCloud();cloudStatus('已同步');updateCloudNote()}catch(e){sb=null;cloudStatus('雲端連線失敗',e.message)}}
async function saveCloudConfig(){let url=$('sbUrl').value.trim(),key=$('sbKey').value.trim();if(!url||!key)return alert('請填 Supabase URL 與 Publishable key');localStorage.setItem(CFG,JSON.stringify({url,key}));await setupCloud()}
async function pushCloud(){if(!sb)return false;let stamp=new Date().toISOString();state._updatedAt=stamp;localStorage.setItem(LS,JSON.stringify(state));let {error}=await sb.from('travel_state').upsert({id:'default',payload:state,updated_at:stamp});if(error){cloudStatus('同步失敗',error.message);return false}lastCloudUpdatedAt=stamp;cloudStatus('已同步');updateCloudNote('已儲存到雲端。');return true}
async function syncNow(){if(!sb)return alert('請先連線 Supabase');try{let {data,error}=await sb.from('travel_state').select('*').eq('id','default').maybeSingle();if(error)throw error;let cloudTime=new Date(data?.updated_at||data?.payload?._updatedAt||0).getTime(),localTime=new Date(state._updatedAt||0).getTime();if(data?.payload?.trips?.length&&cloudTime>localTime){await applyCloudRow(data,true);cloudStatus('已同步');updateCloudNote('已取得雲端最新資料。')}else await pushCloud();alert('同步完成')}catch(e){cloudStatus('同步失敗',e.message);alert('同步失敗：'+e.message)}}
function clearCloudConfig(){localStorage.removeItem(CFG);sb=null;lastCloudUpdatedAt=null;cloudStatus('本機模式');$('cloudNote').className='note';$('cloudNote').textContent='目前使用本機模式。填入 Supabase Project URL 與 Publishable key 後即可同步。'}
function installAutoRefresh(){window.addEventListener('focus',()=>{if(sb)pullLatestCloud(false)});window.addEventListener('pageshow',()=>{if(sb)pullLatestCloud(false)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&sb)pullLatestCloud(false)})}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('tripSelect').onchange=e=>{curTrip=e.target.value;curDate=trip().start;renderAll()};$('mapTripSelect').onchange=e=>{curTrip=e.target.value;curDate=trip().start;renderAll()};$('checkTripSelect').onchange=renderChecks;$('shopTripSelect').onchange=renderShops;try{initMaps()}catch(e){console.error(e)}renderAll();installAutoRefresh();setupCloud();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=8').catch(()=>{})});