/* My Travel Supabase Auth login gate v3 */
(()=>{
 const SUPABASE_URL='https://smgtefydmwoqovhldgvp.supabase.co',SUPABASE_KEY='sb_publishable_GFTHhoVfOHP2edTUSRJa3A_hnevKBeH',sb=window.supabase?.createClient?.(SUPABASE_URL,SUPABASE_KEY);if(!sb){console.error('Supabase client unavailable');return}window.myTravelAuth=sb;let currentUser=null,currentProfile=null;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function ensureStyles(){const s=document.createElement('style');s.textContent=`#authGate{position:fixed;inset:0;z-index:99999;background:linear-gradient(145deg,#0f172a,#0f766e);display:flex;align-items:center;justify-content:center;padding:20px}#authGate.hidden{display:none}.authbox{width:min(430px,100%);background:#fff;border-radius:24px;padding:28px;box-shadow:0 30px 90px rgba(0,0,0,.3)}.authlogo{font-size:30px;font-weight:900;color:#0f172a}.authsub{color:#64748b;margin:4px 0 22px}.authfield{margin-top:12px}.authfield label{display:block;font-size:12px;color:#64748b;margin-bottom:5px}.autherr{display:none;margin-top:12px;padding:10px;border-radius:10px;background:#fff1f0;color:#b42318;font-size:13px}.authuser{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.authrole{font-size:11px;padding:4px 7px;border-radius:999px;background:#ecfdf5;color:#0f766e;font-weight:800}.pw-wrap{position:relative}.pw-wrap input{padding-right:48px}.pw-eye{position:absolute;right:8px;top:50%;transform:translateY(-50%);border:0;background:transparent;width:34px;height:34px;border-radius:9px;font-size:16px}.pw-eye:hover{background:#eef2f7}`;document.head.appendChild(s)}
 function ensureGate(){if(document.getElementById('authGate'))return;const d=document.createElement('div');d.id='authGate';d.innerHTML=`<div class="authbox"><div class="authlogo">✈️ My Travel</div><div class="authsub">登入後才能查看你的旅行</div><form id="authForm"><div class="authfield"><label>Email</label><input id="authEmail" type="email" autocomplete="username" required></div><div class="authfield"><label>密碼</label><input id="authPassword" type="password" autocomplete="current-password" required></div><button id="authLoginBtn" class="btn" style="width:100%;margin-top:18px;padding:12px" type="submit">登入</button><div id="authError" class="autherr"></div></form></div>`;document.body.appendChild(d);d.querySelector('#authForm').addEventListener('submit',login)}
 function ensurePasswordModal(){if(document.getElementById('passwordModal'))return;const m=document.createElement('div');m.id='passwordModal';m.className='modal';m.innerHTML=`<div class="modalbox" style="width:min(540px,100%)"><div class="row between"><div><h2 style="margin:0">修改密碼</h2><div class="muted" style="margin-top:5px">請輸入新密碼並再次確認。</div></div><button class="btn alt" type="button" id="pwClose">✕</button></div><div style="margin-top:18px"><div class="authfield"><label>新密碼</label><div class="pw-wrap"><input id="pwNew" type="password" autocomplete="new-password" placeholder="至少 6 碼"><button class="pw-eye" type="button" data-eye="pwNew" aria-label="顯示或隱藏密碼">👁️</button></div></div><div class="authfield"><label>確認新密碼</label><div class="pw-wrap"><input id="pwConfirm" type="password" autocomplete="new-password" placeholder="再次輸入新密碼"><button class="pw-eye" type="button" data-eye="pwConfirm" aria-label="顯示或隱藏密碼">👁️</button></div></div><div id="pwError" class="autherr"></div></div><div class="row" style="justify-content:flex-end;margin-top:20px"><button class="btn alt" type="button" id="pwCancel">取消</button><button class="btn" type="button" id="pwSave">儲存新密碼</button></div></div>`;document.body.appendChild(m);m.querySelector('#pwClose').onclick=m.querySelector('#pwCancel').onclick=closePasswordModal;m.addEventListener('click',e=>{if(e.target===m)closePasswordModal()});m.querySelectorAll('[data-eye]').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.eye);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'👁️':'🙈'});m.querySelector('#pwSave').onclick=savePassword}
 function closePasswordModal(){const m=document.getElementById('passwordModal');if(!m)return;m.classList.remove('show');['pwNew','pwConfirm'].forEach(id=>{const i=document.getElementById(id);if(i){i.value='';i.type='password'}});const e=document.getElementById('pwError');if(e)e.style.display='none'}
 function showError(msg){const e=document.getElementById('authError');e.textContent=msg;e.style.display='block'}function hideError(){const e=document.getElementById('authError');if(e)e.style.display='none'}
 async function loadProfile(user){const{data,error}=await sb.from('profiles').select('user_id,display_name,system_role').eq('user_id',user.id).single();if(error)throw new Error('帳號已登入，但尚未建立 My Travel 使用者資料');return data}
 async function applySession(session){if(!session?.user){currentUser=null;currentProfile=null;document.getElementById('authGate')?.classList.remove('hidden');renderUser();window.dispatchEvent(new CustomEvent('mytravel-auth-changed',{detail:{user:null,profile:null}}));return}try{const p=await loadProfile(session.user);currentUser=session.user;currentProfile=p;localStorage.setItem('myTravel_person_name',p.display_name);document.getElementById('authGate')?.classList.add('hidden');renderUser();window.dispatchEvent(new CustomEvent('mytravel-auth-changed',{detail:{user:currentUser,profile:p}}));window.dispatchEvent(new CustomEvent('mytravel-person-changed',{detail:{name:p.display_name}}))}catch(e){await sb.auth.signOut();showError(e.message)}}
 async function login(e){e.preventDefault();hideError();const b=document.getElementById('authLoginBtn');b.disabled=true;b.textContent='登入中…';try{const{data,error}=await sb.auth.signInWithPassword({email:document.getElementById('authEmail').value.trim(),password:document.getElementById('authPassword').value});if(error)throw error;await applySession(data.session)}catch(e){showError(e.message==='Invalid login credentials'?'Email 或密碼錯誤':e.message)}finally{b.disabled=false;b.textContent='登入'}}
 async function logout(){await sb.auth.signOut();localStorage.removeItem('myTravel_person_name');currentUser=null;currentProfile=null;document.getElementById('authGate')?.classList.remove('hidden');renderUser()}
 function changePassword(){if(!currentUser)return;ensurePasswordModal();const m=document.getElementById('passwordModal');m.classList.add('show');setTimeout(()=>document.getElementById('pwNew')?.focus(),50)}
 async function savePassword(){const p=document.getElementById('pwNew').value,p2=document.getElementById('pwConfirm').value,e=document.getElementById('pwError'),b=document.getElementById('pwSave');e.style.display='none';if(p.length<6){e.textContent='密碼至少 6 碼';e.style.display='block';return}if(p!==p2){e.textContent='兩次輸入的密碼不一致';e.style.display='block';return}try{b.disabled=true;b.textContent='儲存中…';const{error}=await sb.auth.updateUser({password:p});if(error)throw error;closePasswordModal();alert('密碼已修改完成')}catch(err){e.textContent='密碼修改失敗：'+err.message;e.style.display='block'}finally{b.disabled=false;b.textContent='儲存新密碼'}}
 function renderUser(){const top=document.querySelector('.top');if(!top)return;let box=document.getElementById('authUserBox');if(!box){box=document.createElement('div');box.id='authUserBox';top.appendChild(box)}if(!currentProfile){box.innerHTML='';return}box.innerHTML=`<div class="authuser"><div><b>👤 ${esc(currentProfile.display_name)}</b><div class="authrole">${currentProfile.system_role==='super_admin'?'最高管理員':'一般使用者'}</div></div><button class="btn sm alt" onclick="myTravelChangePassword()">修改密碼</button><button class="btn sm alt" onclick="myTravelLogout()">登出</button></div>`}
 window.myTravelLogout=logout;window.myTravelChangePassword=changePassword;window.myTravelCurrentUser=()=>currentUser;window.myTravelCurrentProfile=()=>currentProfile;window.myTravelPersonName=()=>currentProfile?.display_name||'';window.myTravelIsSuperAdmin=()=>currentProfile?.system_role==='super_admin';
 async function start(){ensureStyles();ensureGate();ensurePasswordModal();const{data}=await sb.auth.getSession();await applySession(data.session);sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')applySession(null);else if(event==='SIGNED_IN'&&session)setTimeout(()=>applySession(session),0)})}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
})();