/* My Travel editor + place search v26 */
(() => {
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let editingId=null,searchTimer=null,searchSeq=0;

  function countryHint(){const s=`${trip()?.name||''} ${trip()?.theme||''}`.toLowerCase();if(/日本|宮古|沖繩|北海道|札幌|東京|大阪|京都|福岡|japan|okinawa|miyako|sapporo|tokyo/.test(s))return'jp';if(/韓國|首爾|釜山|濟州|korea|seoul|busan|jeju/.test(s))return'kr';if(/新加坡|singapore/.test(s))return'sg';if(/台灣|taiwan|taipei|台北/.test(s))return'tw';return''}
  async function searchPlaces(q,limit=6){
    q=(q||'').trim();if(!q)return[];const cc=countryHint(),center=trip()?.center||[];
    const params=new URLSearchParams({format:'jsonv2',limit:String(limit),addressdetails:'1',namedetails:'1',q});if(cc)params.set('countrycodes',cc);
    if(center.length===2&&Number.isFinite(Number(center[0]))&&Number.isFinite(Number(center[1]))){const lat=Number(center[0]),lon=Number(center[1]);params.set('viewbox',`${lon-1.5},${lat+1.5},${lon+1.5},${lat-1.5}`)}
    const r=await fetch(`https://nominatim.openstreetmap.org/search?${params}`,{cache:'no-store',headers:{Accept:'application/json','Accept-Language':'zh-TW,ja,en;q=0.8'}});if(!r.ok)throw new Error('search '+r.status);return await r.json();
  }
  async function geocodeAddress(address,title=''){const qs=[address,title,`${title} ${trip()?.name||''}`].map(x=>(x||'').trim()).filter(Boolean);for(const q of [...new Set(qs)]){try{const a=await searchPlaces(q,1);if(a[0])return{lat:Number(a[0].lat),lng:Number(a[0].lon),display:a[0].display_name||q}}catch(e){console.warn(e)}}return null}

  function ensureEditorModal(){
    $('itemEditModal')?.remove();const m=document.createElement('div');m.id='itemEditModal';m.className='modal';
    m.innerHTML=`<div class="modalbox" style="width:min(760px,100%)"><div class="row between"><h2>編輯行程</h2><button class="btn alt" onclick="closeItemEditor()">✕</button></div>
    <div class="form" style="margin-top:14px"><div><div class="muted" style="margin-bottom:5px">時間</div><input id="editItemTime" type="time"></div><div class="wide"><div class="muted" style="margin-bottom:5px">行程名稱</div><input id="editItemTitle" placeholder="景點／餐廳／交通"></div><div><div class="muted" style="margin-bottom:5px">類型</div><select id="editItemType"><option>景點</option><option>餐廳</option><option>交通</option><option>住宿</option><option>購物</option><option>滑雪</option><option>其他</option></select></div><div class="wide"><div class="muted" style="margin-bottom:5px">備註</div><input id="editItemNote" placeholder="備註"></div>
    <div class="full"><div class="muted" style="margin-bottom:5px">搜尋地點</div><div class="row"><input id="editPlaceSearch" placeholder="輸入 17END、下地島機場、札幌站…"><button id="editPlaceSearchBtn" class="btn alt" type="button">搜尋</button></div><div id="editPlaceResults" style="display:none;margin-top:7px;border:1px solid #d8dee9;border-radius:12px;overflow:hidden"></div></div>
    <div class="full"><div class="muted" style="margin-bottom:5px">地址／地點名稱</div><input id="editItemAddress" placeholder="選擇搜尋結果後會自動帶入，也可自行輸入"></div><div><div class="muted" style="margin-bottom:5px">緯度</div><input id="editItemLat" type="number" step="any"></div><div><div class="muted" style="margin-bottom:5px">經度</div><input id="editItemLng" type="number" step="any"></div></div>
    <div class="row" style="justify-content:flex-end;margin-top:18px"><button class="btn alt" onclick="closeItemEditor()">取消</button><button id="editSaveBtn" class="btn" onclick="saveItemEditor()">儲存修改</button></div></div>`;
    m.addEventListener('click',e=>{if(e.target===m)closeItemEditor()});document.body.appendChild(m);
    $('editPlaceSearchBtn').onclick=()=>runPlaceSearch();$('editPlaceSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();runPlaceSearch()}});$('editPlaceSearch').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(runPlaceSearch,550)});
  }
  async function runPlaceSearch(){
    const input=$('editPlaceSearch'),box=$('editPlaceResults');if(!input||!box)return;const q=input.value.trim();if(q.length<2){box.style.display='none';return}const seq=++searchSeq;box.style.display='block';box.innerHTML='<div class="muted" style="padding:10px">搜尋中…</div>';
    try{let a=await searchPlaces(q,6);if(seq!==searchSeq)return;if(!a.length&&countryHint()){const params=new URLSearchParams({format:'jsonv2',limit:'6',addressdetails:'1',namedetails:'1',q});const r=await fetch(`https://nominatim.openstreetmap.org/search?${params}`,{cache:'no-store',headers:{Accept:'application/json','Accept-Language':'zh-TW,ja,en;q=0.8'}});a=await r.json()}
      if(!a.length){box.innerHTML='<div class="muted" style="padding:10px">找不到地點，可換成景點名稱、英文或日文名稱。</div>';return}
      box.innerHTML=a.map((p,i)=>`<button type="button" data-i="${i}" style="display:block;width:100%;border:0;border-bottom:1px solid #e5e7eb;background:#fff;text-align:left;padding:10px;cursor:pointer"><b>${esc(p.namedetails?.name||p.name||q)}</b><div class="muted" style="margin-top:3px">${esc(p.display_name||'')}</div></button>`).join('');
      [...box.querySelectorAll('button')].forEach(b=>b.onclick=()=>{const p=a[Number(b.dataset.i)];$('editItemAddress').value=p.display_name||q;$('editItemLat').value=p.lat;$('editItemLng').value=p.lon;input.value=p.namedetails?.name||p.name||q;box.style.display='none'});
    }catch(e){console.warn(e);box.innerHTML='<div class="muted" style="padding:10px">目前無法搜尋地點，請稍後再試。</div>'}
  }
  window.editItineraryItem=function(id){ensureEditorModal();const item=(trip().itinerary[curDate]||[]).find(x=>x.id===id);if(!item)return;editingId=id;$('editItemTime').value=item.time||'10:00';$('editItemTitle').value=item.title||'';$('editItemType').value=item.type||'景點';$('editItemNote').value=item.note||'';$('editItemAddress').value=item.address||'';$('editItemLat').value=item.lat??'';$('editItemLng').value=item.lng??'';$('editPlaceSearch').value=item.title||item.address||'';$('itemEditModal').classList.add('show')};
  window.closeItemEditor=function(){editingId=null;$('itemEditModal')?.classList.remove('show')};
  window.saveItemEditor=async function(){if(!editingId)return;const arr=trip().itinerary[curDate]||[],item=arr.find(x=>x.id===editingId);if(!item)return;const title=$('editItemTitle').value.trim();if(!title)return alert('請輸入行程名稱');const address=$('editItemAddress').value.trim();let lat=parseFloat($('editItemLat').value),lng=parseFloat($('editItemLng').value),found=null;const btn=$('editSaveBtn');if(btn){btn.disabled=true;btn.textContent='儲存中…'}if((address||title)&&(!Number.isFinite(lat)||!Number.isFinite(lng)))found=await geocodeAddress(address,title);if(found){lat=found.lat;lng=found.lng}item.time=$('editItemTime').value||'10:00';item.title=title;item.type=$('editItemType').value;item.note=$('editItemNote').value.trim();item.address=address;item.lat=Number.isFinite(lat)?lat:null;item.lng=Number.isFinite(lng)?lng:null;arr.sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));closeItemEditor();save();if(!Number.isFinite(lat)||!Number.isFinite(lng))alert('這個行程還沒有地圖座標，請使用「搜尋地點」選一個結果。')};

  const emergency={jp:{name:'日本',police:'110',fire:'119',ambulance:'119',extras:['JNTO 旅客熱線 050-3816-2787']},kr:{name:'韓國',police:'112',fire:'119',ambulance:'119',extras:['韓國旅遊諮詢 1330']},tw:{name:'台灣',police:'110',fire:'119',ambulance:'119',extras:['外來人士服務專線 1990']},us:{name:'美國',police:'911',fire:'911',ambulance:'911',extras:[]},is:{name:'冰島',police:'112',fire:'112',ambulance:'112',extras:[]},sg:{name:'新加坡',police:'999',fire:'995',ambulance:'995',extras:[]}};
  function guessCountryFromText(t){const s=`${t.name||''} ${t.theme||''}`.toLowerCase();if(/日本|東京|北海道|札幌|宮古|沖繩|大阪|京都|福岡|仙台|名古屋|japan|tokyo|sapporo|okinawa|osaka|kyoto/.test(s))return'jp';if(/韓國|首爾|釜山|濟州|korea|seoul|busan|jeju/.test(s))return'kr';if(/新加坡|singapore/.test(s))return'sg';if(/冰島|iceland/.test(s))return'is';if(/台灣|taiwan|taipei|台北/.test(s))return'tw';return''}
  async function renderTripEmergency(){let card=$('tripEmergencyCard');if(!card){card=document.createElement('div');card.id='tripEmergencyCard';card.className='card';card.style.marginTop='16px';$('tripTools')?.appendChild(card)}if(!card)return;const t=trip(),cc=guessCountryFromText(t),e=emergency[cc];if(!e){card.innerHTML='<h2>緊急聯絡</h2><div class="note">目前尚未建立這個國家的緊急電話資料。</div>';return}card.innerHTML=`<div class="row between"><div><h2>${esc(e.name)}緊急聯絡</h2><div class="muted">依目前選擇的旅行「${esc(t.name)}」自動切換</div></div><span class="pill">${cc.toUpperCase()}</span></div><div class="grid g2" style="margin-top:12px"><div class="setting"><b>👮 警察 ${esc(e.police)}</b></div><div class="setting"><b>🚒 消防 ${esc(e.fire)}</b></div><div class="setting"><b>🚑 救護 ${esc(e.ambulance)}</b></div>${e.extras.map(x=>`<div class="setting"><b>☎️ ${esc(x)}</b></div>`).join('')}</div>`}
  window.refreshTripEmergency=renderTripEmergency;setTimeout(()=>{renderTripEmergency();const s=$('tripSelect');if(s&&!s.dataset.emergencyHook){s.dataset.emergencyHook='1';s.addEventListener('change',()=>setTimeout(renderTripEmergency,100))}},100);
})();