/* My Travel editor - manual Google Maps coordinates v34 */
(() => {
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let editingId=null;
  function parseCoords(v){const text=String(v||'').trim().replace(/，/g,',');const p=text.split(',').map(x=>x.trim()).filter(Boolean);if(p.length<2)return null;const lat=Number(p[0]),lng=Number(p[1]);return Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180?{lat,lng}:null}
  function fillCoords(c){if(!c)return false;const lat=$('editItemLat'),lng=$('editItemLng'),paste=$('editCoordPaste');if(lat)lat.value=c.lat;if(lng)lng.value=c.lng;if(paste)paste.value=`${c.lat}, ${c.lng}`;return true}
  function applyCoords(){const c=parseCoords($('editCoordPaste')?.value);if(!c)return alert('請貼上 Google Maps 經緯度，例如：24.8055, 125.2811');fillCoords(c)}
  function ensureEditorModal(){
    $('itemEditModal')?.remove();const m=document.createElement('div');m.id='itemEditModal';m.className='modal';
    m.innerHTML=`<div class="modalbox" style="width:min(760px,100%)"><div class="row between"><h2>編輯行程</h2><button class="btn alt" onclick="closeItemEditor()">✕</button></div><div class="form" style="margin-top:14px"><div><div class="muted" style="margin-bottom:5px">時間</div><input id="editItemTime" type="time"></div><div class="wide"><div class="muted" style="margin-bottom:5px">行程名稱</div><input id="editItemTitle" placeholder="景點／餐廳／交通"></div><div><div class="muted" style="margin-bottom:5px">類型</div><select id="editItemType"><option>景點</option><option>餐廳</option><option>交通</option><option>住宿</option><option>購物</option><option>滑雪</option><option>其他</option></select></div><div class="wide"><div class="muted" style="margin-bottom:5px">備註</div><input id="editItemNote" placeholder="備註"></div><div class="full"><div class="muted" style="margin-bottom:5px">地址／地點名稱（選填）</div><input id="editItemAddress" placeholder="例如：苗栗中華國宅、17END、札幌站"></div><div class="full"><div class="muted" style="margin-bottom:5px">Google Maps 經緯度</div><div class="row"><input id="editCoordPaste" placeholder="貼上 Google Maps 經緯度，例如 24.8055, 125.2811"><button id="applyCoordBtn" class="btn alt" type="button">套用</button></div><div class="muted" style="margin-top:5px">直接從 Google Maps 複製「緯度, 經度」貼上即可，不再使用 OpenStreetMap 查詢。</div></div><div><div class="muted" style="margin-bottom:5px">緯度</div><input id="editItemLat" type="number" step="any"></div><div><div class="muted" style="margin-bottom:5px">經度</div><input id="editItemLng" type="number" step="any"></div></div><div class="row" style="justify-content:flex-end;margin-top:18px"><button class="btn alt" onclick="closeItemEditor()">取消</button><button id="editSaveBtn" class="btn" onclick="saveItemEditor()">儲存修改</button></div></div>`;
    m.addEventListener('click',e=>{if(e.target===m)closeItemEditor()});document.body.appendChild(m);$('applyCoordBtn').onclick=applyCoords;
    $('editCoordPaste').addEventListener('paste',e=>{const text=e.clipboardData?.getData('text')||'';const c=parseCoords(text);if(c){e.preventDefault();fillCoords(c)}});
    $('editCoordPaste').addEventListener('input',e=>{const c=parseCoords(e.target.value);if(c)fillCoords(c)});
  }
  window.editItineraryItem=function(id){ensureEditorModal();const item=(trip().itinerary[curDate]||[]).find(x=>x.id===id);if(!item)return;editingId=id;$('editItemTime').value=item.time||'10:00';$('editItemTitle').value=item.title||'';$('editItemType').value=item.type||'景點';$('editItemNote').value=item.note||'';$('editItemAddress').value=item.address||'';$('editItemLat').value=item.lat??'';$('editItemLng').value=item.lng??'';$('editCoordPaste').value=(item.lat!=null&&item.lng!=null)?`${item.lat}, ${item.lng}`:'';$('itemEditModal').classList.add('show')};
  window.closeItemEditor=function(){editingId=null;$('itemEditModal')?.classList.remove('show')};
  window.saveItemEditor=function(){if(!editingId)return;const arr=trip().itinerary[curDate]||[],item=arr.find(x=>x.id===editingId);if(!item)return;const title=$('editItemTitle').value.trim();if(!title)return alert('請輸入行程名稱');const address=$('editItemAddress').value.trim();const lat=parseFloat($('editItemLat').value),lng=parseFloat($('editItemLng').value);item.time=$('editItemTime').value||'10:00';item.title=title;item.type=$('editItemType').value;item.note=$('editItemNote').value.trim();item.address=address;item.lat=Number.isFinite(lat)?lat:null;item.lng=Number.isFinite(lng)?lng:null;arr.sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));closeItemEditor();save()};
  const emergency={jp:{name:'日本',police:'110',fire:'119',ambulance:'119',extras:['JNTO 旅客熱線 050-3816-2787']},kr:{name:'韓國',police:'112',fire:'119',ambulance:'119',extras:['韓國旅遊諮詢 1330']},tw:{name:'台灣',police:'110',fire:'119',ambulance:'119',extras:['外來人士服務專線 1990']},us:{name:'美國',police:'911',fire:'911',ambulance:'911',extras:[]},is:{name:'冰島',police:'112',fire:'112',ambulance:'112',extras:[]},sg:{name:'新加坡',police:'999',fire:'995',ambulance:'995',extras:[]}};
  function guessCountryFromText(t){const s=`${t.name||''} ${t.theme||''}`.toLowerCase();if(/日本|東京|北海道|札幌|宮古|沖繩|大阪|京都|福岡|仙台|名古屋|japan|tokyo|sapporo|okinawa|osaka|kyoto/.test(s))return'jp';if(/韓國|首爾|釜山|濟州|korea|seoul|busan|jeju/.test(s))return'kr';if(/新加坡|singapore/.test(s))return'sg';if(/冰島|iceland/.test(s))return'is';if(/台灣|taiwan|taipei|台北/.test(s))return'tw';return''}
  async function renderTripEmergency(){let card=$('tripEmergencyCard');if(!card){card=document.createElement('div');card.id='tripEmergencyCard';card.className='card';card.style.marginTop='16px';$('tripTools')?.appendChild(card)}if(!card)return;const t=trip(),cc=guessCountryFromText(t),e=emergency[cc];if(!e){card.innerHTML='<h2>緊急聯絡</h2><div class="note">目前尚未建立這個國家的緊急電話資料。</div>';return}card.innerHTML=`<div class="row between"><div><h2>${esc(e.name)}緊急聯絡</h2><div class="muted">依目前選擇的旅行「${esc(t.name)}」自動切換</div></div><span class="pill">${cc.toUpperCase()}</span></div><div class="grid g2" style="margin-top:12px"><div class="setting"><b>👮 警察 ${esc(e.police)}</b></div><div class="setting"><b>🚒 消防 ${esc(e.fire)}</b></div><div class="setting"><b>🚑 救護 ${esc(e.ambulance)}</b></div>${e.extras.map(x=>`<div class="setting"><b>☎️ ${esc(x)}</b></div>`).join('')}</div>`}
  window.refreshTripEmergency=renderTripEmergency;setTimeout(()=>{renderTripEmergency();const s=$('tripSelect');if(s&&!s.dataset.emergencyHook){s.dataset.emergencyHook='1';s.addEventListener('change',()=>setTimeout(renderTripEmergency,100))}},100);
})();