/* My Travel multi-currency accounting + multi-payer flexible split v22 */
(() => {
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let moneyTripId=null;
  const currencyInfo={JPY:{symbol:'¥',name:'日圓'},KRW:{symbol:'₩',name:'韓元'},SGD:{symbol:'S$',name:'新加坡幣'},TWD:{symbol:'NT$',name:'新台幣'},USD:{symbol:'US$',name:'美元'},EUR:{symbol:'€',name:'歐元'},GBP:{symbol:'£',name:'英鎊'},AUD:{symbol:'A$',name:'澳幣'},NZD:{symbol:'NZ$',name:'紐西蘭幣'},THB:{symbol:'฿',name:'泰銖'},MYR:{symbol:'RM',name:'馬來西亞令吉'},PHP:{symbol:'₱',name:'菲律賓披索'},VND:{symbol:'₫',name:'越南盾'},HKD:{symbol:'HK$',name:'港幣'},CAD:{symbol:'C$',name:'加拿大幣'},ISK:{symbol:'kr',name:'冰島克朗'}};
  function currencyForTrip(t){const s=`${t?.name||''} ${t?.theme||''}`.toLowerCase();if(/新加坡|singapore/.test(s))return'SGD';if(/韓國|首爾|釜山|濟州|korea|seoul|busan|jeju/.test(s))return'KRW';if(/日本|東京|北海道|札幌|宮古|沖繩|大阪|京都|福岡|仙台|名古屋|japan|tokyo|sapporo|okinawa|osaka|kyoto/.test(s))return'JPY';if(/台灣|taiwan|台北|taipei/.test(s))return'TWD';if(/泰國|曼谷|清邁|thailand|bangkok/.test(s))return'THB';if(/馬來西亞|吉隆坡|malaysia|kuala lumpur/.test(s))return'MYR';if(/菲律賓|馬尼拉|philippines|manila/.test(s))return'PHP';if(/越南|河內|胡志明|vietnam|hanoi/.test(s))return'VND';if(/香港|hong kong/.test(s))return'HKD';if(/冰島|iceland|reykjavik/.test(s))return'ISK';if(/澳洲|australia|sydney|melbourne/.test(s))return'AUD';if(/紐西蘭|new zealand|auckland/.test(s))return'NZD';if(/加拿大|canada/.test(s))return'CAD';if(/英國|united kingdom|london/.test(s))return'GBP';if(/法國|德國|義大利|西班牙|france|germany|italy|spain|paris|berlin|rome|madrid|barcelona/.test(s))return'EUR';if(/美國|usa|united states|new york|los angeles/.test(s))return'USD';return'JPY'}
  function curTrip(){return state.trips.find(t=>t.id===moneyTripId)||trip()}
  function info(c){return currencyInfo[c]||{symbol:c+' ',name:c}}
  function fmtMoney(n,c){return info(c).symbol+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:c==='TWD'?0:2})}
  function getRate(c){if(c==='TWD')return 1;state.fxRates=state.fxRates||{};return Number(state.fxRates[c]?.rate||(c==='JPY'?state.rate:0))||0}
  function ensurePeople(t){if(!Array.isArray(t.people))t.people=[];return t.people}
  function pName(t,id){return ensurePeople(t).find(p=>p.id===id)?.name||'未指定'}
  function normalizedPayments(e,t){if(Array.isArray(e.payments)&&e.payments.length)return e.payments;if(e.payerId)return[{personId:e.payerId,amount:Number(e.amount)||0}];return[]}
  function normalizedShares(e,t){const people=ensurePeople(t),amount=Number(e.amount)||0;if(Array.isArray(e.shares)&&e.shares.length)return e.shares;if(!people.length)return[];return people.map(p=>({personId:p.id,amount:amount/people.length}))}

  function ensureMoneySelector(){const page=$('money');if(!page)return;let box=$('moneyTripBar');if(!box){box=document.createElement('div');box.id='moneyTripBar';box.className='card';box.style.marginBottom='16px';box.innerHTML=`<div class="row between"><div><h2 style="margin:0">旅行帳本</h2><div class="muted" id="moneyTripMeta"></div></div><select id="moneyTripSelect" style="width:min(260px,45vw)"></select></div>`;page.insertBefore(box,page.firstChild);$('moneyTripSelect').addEventListener('change',async e=>{moneyTripId=e.target.value;await refreshTripFx(false);renderMoney()})}const sel=$('moneyTripSelect');sel.innerHTML=state.trips.map(t=>`<option value="${t.id}">${esc(t.emoji||'✈️')} ${esc(t.name)}</option>`).join('');if(!moneyTripId||!state.trips.some(t=>t.id===moneyTripId))moneyTripId=trip()?.id||state.trips[0]?.id;sel.value=moneyTripId}
  function ensurePeoplePanel(){const bar=$('moneyTripBar');if(!bar)return;let panel=$('moneyPeoplePanel');if(!panel){panel=document.createElement('div');panel.id='moneyPeoplePanel';panel.className='card';panel.style.marginBottom='16px';panel.innerHTML=`<div class="row between"><div><h2 style="margin:0">旅伴與分帳</h2><div class="muted">每筆可由多人付款，也可選擇不同分攤方式</div></div><div class="row"><button class="btn alt" onclick="openPersonModal()">＋新增人員</button><button class="btn" onclick="showSettlement()">結算</button></div></div><div id="moneyPeopleList" class="row" style="margin-top:12px;flex-wrap:wrap"></div>`;bar.after(panel)}}
  function ensureExpenseControls(){const form=$('eDate')?.closest('.form');if(!form)return;form.classList.add('expense-form-v22');$('ePayer')?.remove();if(!$('splitMode')){const btn=document.createElement('button');btn.type='button';btn.id='splitMode';btn.className='btn alt';btn.textContent='設定付款／分攤';btn.onclick=()=>openExpenseSplitSetup();$('eAmount').after(btn)}if(!$('money-v22-style')){const st=document.createElement('style');st.id='money-v22-style';st.textContent=`.expense-form-v22{grid-template-columns:repeat(5,minmax(0,1fr))!important}.person-chip{display:flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid var(--line);border-radius:999px;background:#fff}.person-chip button{border:0;background:transparent;color:#b42318;cursor:pointer;font-weight:800}.split-person{display:grid;grid-template-columns:30px 1fr minmax(100px,160px);gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.split-person input[type=number]{width:100%}.split-tabs{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.split-tabs button.active{background:#087f78;color:#fff}.settle-row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:12px;border:1px solid var(--line);border-radius:12px;margin-top:8px}@media(max-width:900px){.expense-form-v22{grid-template-columns:1fr!important}#moneyPeoplePanel>.row.between{align-items:flex-start;flex-direction:column}#moneyPeoplePanel>.row.between>.row{width:100%}#moneyPeoplePanel>.row.between>.row .btn{flex:1}.split-person{grid-template-columns:28px 1fr 110px}}`;document.head.appendChild(st)}}
  function renderPeople(){const t=curTrip(),people=ensurePeople(t),list=$('moneyPeopleList');if(!list)return;list.innerHTML=people.length?people.map(p=>`<div class="person-chip"><span>👤 ${esc(p.name)}</span><button onclick="deletePerson('${p.id}')">×</button></div>`).join(''):'<span class="muted">尚未新增旅伴</span>'}
  function ensureSplitModal(){if($('splitModal'))return;const m=document.createElement('div');m.id='splitModal';m.className='modal';m.innerHTML=`<div class="modalbox" style="width:min(720px,100%)"><div class="row between"><h2 id="splitTitle"></h2><button class="btn alt" onclick="closeSplitModal()">✕</button></div><div id="splitBody" style="margin-top:14px"></div><div class="row" id="splitFooter" style="justify-content:flex-end;margin-top:18px"></div></div>`;m.addEventListener('click',e=>{if(e.target===m)closeSplitModal()});document.body.appendChild(m)}
  window.closeSplitModal=()=>{$('splitModal')?.classList.remove('show')};
  window.openPersonModal=function(){if(!$('universalModal')){const n=prompt('人員名稱');if(n?.trim())addPersonName(n.trim());return}$('uTitle').textContent='新增旅伴';$('uBody').innerHTML='<div class="full"><label>姓名／暱稱</label><input id="newPersonName" placeholder="例如：DIN、胖胖"></div>';$('uSave').onclick=()=>{const n=$('newPersonName').value.trim();if(!n)return alert('請輸入名稱');addPersonName(n);closeUniversalModal()};$('universalModal').classList.add('show')};
  function addPersonName(name){const t=curTrip(),ps=ensurePeople(t);if(ps.some(p=>p.name.toLowerCase()===name.toLowerCase()))return alert('這個人員已存在');ps.push({id:crypto.randomUUID(),name});save();setTimeout(renderMoney,0)}
  window.deletePerson=function(id){const t=curTrip(),p=ensurePeople(t).find(x=>x.id===id);if(!p)return;const used=state.expenses.some(e=>e.tripId===t.id&&(e.payerId===id||e.payments?.some(x=>x.personId===id)||e.shares?.some(x=>x.personId===id)));if(used)return alert(`「${p.name}」已有付款或分攤紀錄，請先修改相關支出。`);if(confirm(`刪除旅伴「${p.name}」？`)){t.people=t.people.filter(x=>x.id!==id);save();renderMoney()}};

  async function refreshTripFx(force=false){const t=curTrip(),code=currencyForTrip(t);state.fxRates=state.fxRates||{};const today=new Date().toISOString().slice(0,10),old=state.fxRates[code];if(code==='TWD'){state.fxRates.TWD={rate:1,date:today};return 1}if(!force&&old?.date===today&&old?.rate)return old.rate;try{const r=await fetch(`https://api.frankfurter.dev/v2/rate/${code}/TWD`,{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json(),rate=Number(d.rate);state.fxRates[code]={rate,date:d.date||today};if(code==='JPY')state.rate=rate;localStorage.setItem(LS,JSON.stringify(state));if(sb)pushCloud();return rate}catch(e){return getRate(code)}}
  window.refreshTripFx=async()=>{await refreshTripFx(true);renderMoney()};window.refreshDailyFx=window.refreshTripFx;

  let draftSplit=null;
  window.openExpenseSplitSetup=function(existingId=null){ensureSplitModal();const t=curTrip(),people=ensurePeople(t),code=currencyForTrip(t);if(!people.length)return alert('請先新增旅伴');const e=existingId?state.expenses.find(x=>x.id===existingId):null;const amount=Number(existingId?e?.amount:$('eAmount')?.value)||0;if(amount<=0)return alert('請先輸入總金額');const oldPays=e?normalizedPayments(e,t):[];const oldShares=e?normalizedShares(e,t):[];draftSplit={expenseId:existingId,amount,payments:Object.fromEntries(people.map(p=>[p.id,oldPays.find(x=>x.personId===p.id)?.amount||0])),mode:e?.splitMode||'all',shares:Object.fromEntries(people.map(p=>[p.id,oldShares.find(x=>x.personId===p.id)?.amount||0]))};renderSplitEditor(code)};
  function renderSplitEditor(code){const t=curTrip(),people=ensurePeople(t),d=draftSplit;$('splitTitle').textContent='付款與分攤設定';$('splitBody').innerHTML=`<h3>誰付款？</h3><div class="muted">可勾選多位付款人，右側輸入各自實際付款金額。付款合計需等於 ${fmtMoney(d.amount,code)}</div><div>${people.map(p=>`<div class="split-person"><input type="checkbox" class="pay-check" data-id="${p.id}" ${d.payments[p.id]>0?'checked':''}><b>${esc(p.name)}</b><input type="number" class="pay-amt" data-id="${p.id}" min="0" step="0.01" value="${d.payments[p.id]||''}" placeholder="付款金額"></div>`).join('')}</div><h3 style="margin-top:18px">怎麼分攤？</h3><div class="split-tabs"><button class="btn alt ${d.mode==='all'?'active':''}" onclick="setSplitMode('all')">全部平均</button><button class="btn alt ${d.mode==='selected'?'active':''}" onclick="setSplitMode('selected')">指定人員平均</button><button class="btn alt ${d.mode==='custom'?'active':''}" onclick="setSplitMode('custom')">自訂金額</button><button class="btn alt ${d.mode==='personal'?'active':''}" onclick="setSplitMode('personal')">個人支出</button></div><div id="shareEditor">${shareEditorHtml(people,d,code)}</div>`;$('splitFooter').innerHTML='<button class="btn alt" onclick="closeSplitModal()">取消</button><button class="btn" onclick="saveSplitDraft()">套用</button>';$('splitModal').classList.add('show')}
  function shareEditorHtml(people,d,code){if(d.mode==='all')return`<div class="note good">${people.length} 人平均，每人約 ${fmtMoney(d.amount/people.length,code)}</div>`;if(d.mode==='selected')return people.map(p=>`<label class="split-person"><input type="checkbox" class="share-check" data-id="${p.id}" ${d.shares[p.id]>0?'checked':''}><b>${esc(p.name)}</b><span class="muted">參與分攤</span></label>`).join('');if(d.mode==='personal')return`<label>由誰負擔？</label><select id="personalPerson">${people.map(p=>`<option value="${p.id}" ${d.shares[p.id]===d.amount?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`;return people.map(p=>`<div class="split-person"><span>👤</span><b>${esc(p.name)}</b><input type="number" class="share-amt" data-id="${p.id}" min="0" step="0.01" value="${d.shares[p.id]||''}" placeholder="分攤金額"></div>`).join('')}
  function captureDraft(){if(!draftSplit)return;document.querySelectorAll('.pay-amt').forEach(x=>{const id=x.dataset.id,checked=document.querySelector(`.pay-check[data-id="${id}"]`)?.checked;draftSplit.payments[id]=checked?(Number(x.value)||0):0});if(draftSplit.mode==='selected')document.querySelectorAll('.share-check').forEach(x=>draftSplit.shares[x.dataset.id]=x.checked?1:0);if(draftSplit.mode==='custom')document.querySelectorAll('.share-amt').forEach(x=>draftSplit.shares[x.dataset.id]=Number(x.value)||0)}
  window.setSplitMode=function(mode){captureDraft();draftSplit.mode=mode;const t=curTrip();if(mode==='all')ensurePeople(t).forEach(p=>draftSplit.shares[p.id]=draftSplit.amount/ensurePeople(t).length);if(mode==='custom')ensurePeople(t).forEach(p=>draftSplit.shares[p.id]=0);renderSplitEditor(currencyForTrip(t))};
  window.saveSplitDraft=function(){captureDraft();const t=curTrip(),people=ensurePeople(t),d=draftSplit;const pays=people.map(p=>({personId:p.id,amount:Number(d.payments[p.id])||0})).filter(x=>x.amount>0),payTotal=pays.reduce((s,x)=>s+x.amount,0);if(Math.abs(payTotal-d.amount)>0.01)return alert(`付款合計 ${fmtMoney(payTotal,currencyForTrip(t))}，必須等於總金額 ${fmtMoney(d.amount,currencyForTrip(t))}`);let shares=[];if(d.mode==='all')shares=people.map(p=>({personId:p.id,amount:d.amount/people.length}));else if(d.mode==='selected'){const ids=people.filter(p=>d.shares[p.id]>0);if(!ids.length)return alert('請至少選一位分攤人員');shares=ids.map(p=>({personId:p.id,amount:d.amount/ids.length}))}else if(d.mode==='personal'){const id=$('personalPerson').value;shares=[{personId:id,amount:d.amount}]}else{shares=people.map(p=>({personId:p.id,amount:Number(d.shares[p.id])||0})).filter(x=>x.amount>0);const total=shares.reduce((s,x)=>s+x.amount,0);if(Math.abs(total-d.amount)>0.01)return alert(`分攤合計 ${fmtMoney(total,currencyForTrip(t))}，必須等於總金額 ${fmtMoney(d.amount,currencyForTrip(t))}`)}d.finalPayments=pays;d.finalShares=shares;closeSplitModal();if(d.expenseId){const e=state.expenses.find(x=>x.id===d.expenseId);e.payments=pays;e.shares=shares;e.splitMode=d.mode;delete e.payerId;save();renderMoney()}else{$('splitMode').textContent=`已設定付款 ${pays.length} 人／${d.mode==='all'?'全部平均':d.mode==='selected'?'指定平均':d.mode==='custom'?'自訂金額':'個人支出'}`}};

  window.addExpense=function(){const t=curTrip(),code=currencyForTrip(t),n=$('eName').value.trim(),a=Number($('eAmount').value);if(!n||a<=0)return alert('請輸入支出名稱與金額');if(!draftSplit?.finalPayments||draftSplit.amount!==a)return alert('請先按「設定付款／分攤」完成付款與分攤設定');state.expenses.push({id:crypto.randomUUID(),tripId:t.id,date:$('eDate').value,cat:$('eCat').value,name:n,amount:a,currency:code,payments:draftSplit.finalPayments,shares:draftSplit.finalShares,splitMode:draftSplit.mode});$('eName').value='';$('eAmount').value='';draftSplit=null;$('splitMode').textContent='設定付款／分攤';save();renderMoney()};
  window.editSplitExpense=function(id){const e=state.expenses.find(x=>x.id===id);if(!e)return;openExpenseSplitSetup(id)};

  window.showSettlement=function(){ensureSplitModal();const t=curTrip(),people=ensurePeople(t),code=currencyForTrip(t),rate=getRate(code),list=state.expenses.filter(e=>e.tripId===t.id);if(people.length<2)return alert('至少需要 2 位旅伴');if(!list.length)return alert('目前沒有支出');const bal=Object.fromEntries(people.map(p=>[p.id,0]));let valid=0;list.forEach(e=>{const pays=normalizedPayments(e,t),shares=normalizedShares(e,t);if(!pays.length||!shares.length)return;valid++;pays.forEach(x=>{if(x.personId in bal)bal[x.personId]+=Number(x.amount)||0});shares.forEach(x=>{if(x.personId in bal)bal[x.personId]-=Number(x.amount)||0})});const cr=people.map(p=>({name:p.name,amt:bal[p.id]})).filter(x=>x.amt>.005).sort((a,b)=>b.amt-a.amt),db=people.map(p=>({name:p.name,amt:-bal[p.id]})).filter(x=>x.amt>.005).sort((a,b)=>b.amt-a.amt),tr=[];let i=0,j=0;while(i<db.length&&j<cr.length){const a=Math.min(db[i].amt,cr[j].amt);tr.push({from:db[i].name,to:cr[j].name,amount:a});db[i].amt-=a;cr[j].amt-=a;if(db[i].amt<.005)i++;if(cr[j].amt<.005)j++}$('splitTitle').textContent=`${t.name} · 結算`;$('splitBody').innerHTML=`<div class="note good">已依每筆實際付款與分攤方式計算 · ${valid} 筆支出</div>${tr.length?tr.map(x=>`<div class="settle-row"><div><b>${esc(x.from)}</b> 要給 <b>${esc(x.to)}</b></div><div><b>${fmtMoney(x.amount,code)}</b>${rate&&code!=='TWD'?`<div class="muted">約 ${fmtMoney(x.amount*rate,'TWD')}</div>`:''}</div></div>`).join(''):'<div class="empty">目前已經結清 🎉</div>'}`;$('splitFooter').innerHTML='<button class="btn" onclick="closeSplitModal()">完成</button>';$('splitModal').classList.add('show')};

  window.renderMoney=function(){ensureMoneySelector();ensurePeoplePanel();ensureExpenseControls();ensureSplitModal();const t=curTrip(),code=currencyForTrip(t),ci=info(code),rate=getRate(code),list=state.expenses.filter(e=>e.tripId===t.id);let sum=list.reduce((s,e)=>s+(Number(e.amount)||0),0);const cards=[...$('money').querySelectorAll(':scope > .grid.g4 > .card')];if(cards[0]){cards[0].querySelector('.muted').textContent=`總支出 ${code}`;$('sumJPY').textContent=fmtMoney(sum,code)}if(cards[1]){cards[1].querySelector('.muted').textContent='約合 TWD';$('sumTWD').textContent=fmtMoney(rate?sum*rate:0,'TWD')}$('sumCount').textContent=list.length;if(cards[3]){cards[3].querySelector('.muted').textContent=`${code} → TWD 換算匯率`;$('rate').value=rate||'';$('rate').disabled=true;let st=cards[3].querySelector('#fxStatus');if(!st){st=document.createElement('div');st.id='fxStatus';cards[3].appendChild(st)}st.innerHTML=`<div class="muted" style="margin-top:8px">每日網路參考匯率${state.fxRates?.[code]?.date?' · '+state.fxRates[code].date:''}</div><button class="btn sm alt" onclick="refreshTripFx()">↻ 更新匯率</button>`}$('moneyTripMeta').textContent=`${t.name} · ${t.start} ～ ${t.end} · 使用 ${code}（${ci.name}）`;$('eDate').min=t.start;$('eDate').max=t.end;if(!$('eDate').value||$('eDate').value<t.start||$('eDate').value>t.end)$('eDate').value=t.start;$('eAmount').placeholder=`${code} 金額`;renderPeople();const table=$('expenseRows')?.closest('table');if(table)table.querySelector('thead').innerHTML=`<tr><th>日期</th><th>分類</th><th>項目</th><th>付款</th><th>分攤</th><th>${code}</th><th>TWD</th><th></th></tr>`;$('expenseRows').innerHTML=list.map(e=>{const pays=normalizedPayments(e,t).map(x=>`${pName(t,x.personId)} ${fmtMoney(x.amount,e.currency||code)}`).join('、')||'未設定';const shares=normalizedShares(e,t).map(x=>`${pName(t,x.personId)} ${fmtMoney(x.amount,e.currency||code)}`).join('、')||'未設定';return`<tr><td>${esc(e.date)}</td><td>${esc(e.cat)}</td><td>${esc(e.name)}</td><td>${esc(pays)}</td><td>${esc(shares)}</td><td>${fmtMoney(e.amount,e.currency||code)}</td><td>${fmtMoney((Number(e.amount)||0)*(getRate(e.currency||code)||rate),'TWD')}</td><td><div class="row"><button class="btn sm alt" onclick="editSplitExpense('${e.id}')">付款/分攤</button><button class="btn sm red" onclick="delExpense('${e.id}')">刪除</button></div></td></tr>`}).join('')};
  document.querySelectorAll('[data-page="money"]').forEach(b=>b.addEventListener('click',()=>setTimeout(async()=>{ensureMoneySelector();await refreshTripFx(false);renderMoney()},80)));document.addEventListener('DOMContentLoaded',()=>setTimeout(async()=>{ensureMoneySelector();await refreshTripFx(false);renderMoney()},400));
})();