/* My Travel checklist reminders v6 - per-user checklist isolation */
(()=>{
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pad=n=>String(n).padStart(2,'0');
 const reminderText=v=>{if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString('zh-TW',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})};
 let reminderCtx=null,checkEditCtx=null;
 const me=()=>window.myTravelCurrentProfile?.()||null;
 const myUserId=()=>me()?.user_id||'';
 const myName=()=>me()?.display_name||'';
 const personForUser=id=>(state.people||[]).find(p=>p.user_id===id);
 function isTripMember(t){const p=personForUser(myUserId())||(state.people||[]).find(p=>p.name===myName());return !!p&&(t.memberIds||[]).includes(p.id)}
 function owns(i){const uid=myUserId(),name=myName();if(!uid)return false;if(i.owner_user_id)return i.owner_user_id===uid;if(i.user_id)return i.user_id===uid;if(i.ownerName)return i.ownerName===name;if(i.person_name)return i.person_name===name;return false}
 function normalizeChecks(){for(const t of state.trips||[])for(const i of t.checks||[]){if(!('remindAt'in i))i.remindAt=null;if(!('notifiedAt'in i))i.notifiedAt=null;if(!('lastNotifiedAt'in i))i.lastNotifiedAt=i.notifiedAt||null;if(!i.owner_user_id){if(i.user_id)i.owner_user_id=i.user_id;else if(i.ownerName){const p=(state.people||[]).find(x=>x.name===i.ownerName);if(p?.user_id)i.owner_user_id=p.user_id}}}}
 function allowed(t,i){return isTripMember(t)&&owns(i)}
 function findMine(tid,id){normalizeChecks();const t=(state.trips||[]).find(x=>x.id===tid),i=t?.checks?.find(x=>x.id===id);return t&&i&&allowed(t,i)?{t,i}:null}
 function overdueItems(){normalizeChecks();const now=Date.now(),out=[];for(const t of state.trips||[]){if(!isTripMember(t))continue;for(const i of t.checks||[]){if(!owns(i))continue;const due=i.remindAt?new Date(i.remindAt).getTime():NaN;if(!i.done&&Number.isFinite(due)&&due<=now)out.push({trip:t,item:i,due})}}return out.sort((a,b)=>a.due-b.due)}
 async function enableNotifications(){if(!('Notification'in window))return alert('這個瀏覽器不支援系統通知');if(!window.isSecureContext)return alert('系統通知需要 HTTPS');const p=await Notification.requestPermission();if(p==='granted')renderNotificationStatus();else alert(p==='denied'?'你已拒絕通知權限，可到瀏覽器／系統設定重新開啟。':'尚未允許通知。')}
 window.enableTravelNotifications=enableNotifications;
 function ensureReminderModal(){if($('reminderModal'))return;const m=document.createElement('div');m.id='reminderModal';m.className='modal';m.innerHTML=`<div class="modalbox" style="width:min(620px,100%)"><div class="row between"><div><h2 style="margin:0">設定行前提醒</h2><div class="muted" style="margin-top:4px">此提醒只屬於目前登入帳號。</div></div><button class="btn alt" type="button" onclick="closeReminderEditor()">✕</button></div><div class="modalgrid" style="margin-top:18px"><div class="full"><label>待辦事項</label><input id="reminderItemName" readonly></div><div><label>提醒日期</label><input id="reminderDate" type="date"></div><div><label>提醒時間</label><input id="reminderTime" type="time" step="60"></div></div><div class="row" style="justify-content:space-between;margin-top:18px"><button id="removeReminderBtn" class="btn red" type="button" onclick="removeCurrentReminder()">取消提醒</button><div class="row"><button class="btn alt" type="button" onclick="closeReminderEditor()">取消</button><button class="btn" type="button" onclick="saveReminderEditor()">儲存提醒</button></div></div></div>`;m.addEventListener('click',e=>{if(e.target===m)closeReminderEditor()});document.body.appendChild(m)}
 function ensureCheckEditModal(){if($('checkEditModal'))return;const m=document.createElement('div');m.id='checkEditModal';m.className='modal';m.innerHTML=`<div class="modalbox" style="width:min(680px,100%)"><div class="row between"><div><h2 style="margin:0">編輯行前事項</h2><div class="muted">只能修改自己的待辦。</div></div><button class="btn alt" type="button" onclick="closeCheckEditor()">✕</button></div><div class="modalgrid" style="margin-top:18px"><div class="full"><label>待辦內容</label><input id="checkEditName"></div><div><label>提醒日期</label><input id="checkEditDate" type="date"></div><div><label>提醒時間</label><input id="checkEditTime" type="time" step="60"></div><div class="full"><label class="row"><input id="checkEditDone" type="checkbox" style="width:auto"><span>已完成</span></label></div></div><div class="row" style="justify-content:flex-end;margin-top:18px"><button class="btn alt" type="button" onclick="closeCheckEditor()">取消</button><button class="btn" type="button" onclick="saveCheckEditor()">儲存修改</button></div></div>`;m.addEventListener('click',e=>{if(e.target===m)closeCheckEditor()});document.body.appendChild(m)}
 window.closeReminderEditor=()=>{reminderCtx=null;$('reminderModal')?.classList.remove('show')};window.closeCheckEditor=()=>{checkEditCtx=null;$('checkEditModal')?.classList.remove('show')};
 window.editCheckReminder=(tid,id)=>{const x=findMine(tid,id);if(!x)return alert('你沒有權限修改這個待辦');ensureReminderModal();reminderCtx={tid,id};$('reminderItemName').value=x.i.name||'';let d=x.i.remindAt?new Date(x.i.remindAt):new Date(Date.now()+1800000);$('reminderDate').value=`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;$('reminderTime').value=`${pad(d.getHours())}:${pad(d.getMinutes())}`;$('removeReminderBtn').style.visibility=x.i.remindAt?'visible':'hidden';$('reminderModal').classList.add('show')};
 window.saveReminderEditor=()=>{if(!reminderCtx)return;const x=findMine(reminderCtx.tid,reminderCtx.id);if(!x)return alert('你沒有權限修改這個待辦');const date=$('reminderDate').value,time=$('reminderTime').value;if(!date||!time)return alert('請選擇提醒日期與時間');const d=new Date(`${date}T${time}:00`);x.i.remindAt=d.toISOString();x.i.notifiedAt=null;x.i.lastNotifiedAt=null;closeReminderEditor();save();refresh()};
 window.removeCurrentReminder=()=>{if(!reminderCtx)return;const x=findMine(reminderCtx.tid,reminderCtx.id);if(!x)return;x.i.remindAt=null;x.i.notifiedAt=null;x.i.lastNotifiedAt=null;closeReminderEditor();save();refresh()};
 window.editCheckName=(tid,id)=>{const x=findMine(tid,id);if(!x)return alert('你沒有權限修改這個待辦');ensureCheckEditModal();checkEditCtx={tid,id};$('checkEditName').value=x.i.name||'';$('checkEditDone').checked=!!x.i.done;const d=x.i.remindAt?new Date(x.i.remindAt):null;$('checkEditDate').value=d?`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`:'';$('checkEditTime').value=d?`${pad(d.getHours())}:${pad(d.getMinutes())}`:'';$('checkEditModal').classList.add('show')};
 window.saveCheckEditor=()=>{if(!checkEditCtx)return;const x=findMine(checkEditCtx.tid,checkEditCtx.id);if(!x)return alert('你沒有權限修改這個待辦');const name=$('checkEditName').value.trim(),date=$('checkEditDate').value,time=$('checkEditTime').value;if(!name)return alert('請輸入待辦內容');if((date&&!time)||(!date&&time))return alert('提醒日期與時間請一起填寫');x.i.name=name;x.i.done=$('checkEditDone').checked;x.i.remindAt=date&&time?new Date(`${date}T${time}:00`).toISOString():null;x.i.notifiedAt=null;x.i.lastNotifiedAt=null;closeCheckEditor();save();refresh()};
 function renderNotificationStatus(){let box=$('travelNotificationStatus');if(!box){const c=$('checkRows')?.closest('.card');if(!c)return;box=document.createElement('div');box.id='travelNotificationStatus';box.className='setting';box.style.marginBottom='10px';$('checkInput')?.closest('.row')?.before(box)}const p='Notification'in window?Notification.permission:'unsupported';box.innerHTML=`<div class="row between"><div><b>${p==='granted'?'✅ 裝置通知已開啟':'🔔 裝置通知'}</b><div class="muted">登入：${esc(myName()||'尚未登入')}，只顯示及推送自己的待辦。</div></div>${p!=='granted'&&p!=='unsupported'?'<button class="btn sm" onclick="enableTravelNotifications()">開啟通知</button>':''}</div>`}
 window.renderChecks=()=>{normalizeChecks();const rows=$('checkRows');if(!rows)return;const t=(state.trips||[]).find(x=>x.id===$('checkTripSelect')?.value)||trip();if(!t||!isTripMember(t)){rows.innerHTML='<div class="muted">目前沒有可查看的旅行待辦。</div>';renderOverdueHome();return}const list=(t.checks||[]).filter(owns);rows.innerHTML=list.length?list.map(i=>`<div class="check ${i.done?'done':''}" style="align-items:flex-start"><input type="checkbox" ${i.done?'checked':''} onchange="completeOverdueCheck('${t.id}','${i.id}',this.checked)"><div style="flex:1"><span>${esc(i.name)}</span>${i.remindAt?`<div class="muted">🔔 ${esc(reminderText(i.remindAt))}</div>`:''}</div><div class="row"><button class="btn sm alt" onclick="editCheckReminder('${t.id}','${i.id}')">${i.remindAt?'提醒':'＋提醒'}</button><button class="btn sm alt" onclick="editCheckName('${t.id}','${i.id}')">編輯</button><button class="btn sm red" onclick="deleteCheckItem('${t.id}','${i.id}')">刪除</button></div></div>`).join(''):'<div class="muted">你在這趟旅行還沒有待辦事項。</div>';renderNotificationStatus();renderOverdueHome()};
 window.addCheck=()=>{const n=$('checkInput')?.value.trim(),uid=myUserId();if(!n||!uid)return;const t=(state.trips||[]).find(x=>x.id===$('checkTripSelect')?.value)||trip();if(!t||!isTripMember(t))return alert('你沒有這趟旅行的權限');t.checks=t.checks||[];t.checks.push({id:crypto.randomUUID(),name:n,done:false,remindAt:null,notifiedAt:null,lastNotifiedAt:null,owner_user_id:uid,ownerName:myName()});$('checkInput').value='';save();refresh()};
 window.deleteCheckItem=(tid,id)=>{const x=findMine(tid,id);if(!x)return alert('你沒有權限刪除這個待辦');if(!confirm(`刪除「${x.i.name}」？`))return;x.t.checks=x.t.checks.filter(i=>i.id!==id);save();refresh()};
 window.completeOverdueCheck=(tid,id,checked=true)=>{const x=findMine(tid,id);if(!x)return;x.i.done=checked!==false;save();refresh()};
 function ensureOverdueCard(){let c=$('homeOverdueCard');if(c)return c;const home=$('home');if(!home)return null;c=document.createElement('div');c.id='homeOverdueCard';c.className='card';c.style.marginTop='18px';const cards=$('tripCards');cards?home.insertBefore(c,cards):home.appendChild(c);return c}
 function renderOverdueHome(){const c=ensureOverdueCard();if(!c)return;const list=overdueItems();if(!list.length){c.style.display='none';c.innerHTML='';return}c.style.display='block';c.innerHTML=`<div class="row between"><div><h2 style="margin:0">⚠️ 已過期未完成</h2><div class="muted">${esc(myName())} 的 ${list.length} 項逾期待辦</div></div><span class="pill">${list.length}</span></div><div style="margin-top:10px">${list.map(x=>`<div class="setting" style="margin-top:8px"><div class="row between"><label class="row" style="flex:1"><input type="checkbox" style="width:auto" onchange="completeOverdueCheck('${x.trip.id}','${x.item.id}',this.checked)"><div><b>${esc(x.item.name)}</b><div class="muted">${esc(x.trip.emoji||'✈️')} ${esc(x.trip.name)} ・ ${esc(reminderText(x.item.remindAt))}</div></div></label><button class="btn sm alt" onclick="editCheckReminder('${x.trip.id}','${x.item.id}')">修改提醒</button></div></div>`).join('')}</div>`}
 window.renderOverdueHome=renderOverdueHome;
 function refresh(){setTimeout(()=>{try{renderChecks()}catch(e){};renderOverdueHome()},30)}
 normalizeChecks();ensureReminderModal();ensureCheckEditModal();const start=()=>setTimeout(refresh,450);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();window.addEventListener('mytravel-auth-changed',()=>{reminderCtx=null;checkEditCtx=null;$('checkRows')&&($('checkRows').innerHTML='');const c=$('homeOverdueCard');if(c){c.innerHTML='';c.style.display='none'};setTimeout(refresh,500)});window.addEventListener('mytravel-person-changed',()=>setTimeout(refresh,100));window.addEventListener('mytravel-cloud-applied',()=>setTimeout(refresh,100));window.addEventListener('pageshow',refresh);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh()});
})();