/* My Travel effective permission UI v2 */
(()=>{
 const has=k=>window.myTravelHasPermission?.(k)===true,admin=()=>window.myTravelIsSuperAdmin?.()===true,uid=()=>window.myTravelCurrentProfile?.()?.user_id||'',own=r=>admin()||r?.created_by===uid()||r?.owner_user_id===uid();
 const t=()=>typeof trip==='function'?trip():(state.trips||[]).find(x=>x.id===curTrip);function toggle(el,on){if(el)el.style.display=on?'':'none'}
 function apply(){const ct=t();document.querySelectorAll('.addtrip').forEach(x=>toggle(x,admin()||has('trip.add')));document.querySelectorAll('[onclick^="openTripEditor("]').forEach(b=>{const m=b.getAttribute('onclick')?.match(/openTripEditor\(['\"]?([^'\")]+)?/),r=m?.[1]?state.trips.find(x=>String(x.id)===m[1]):null;toggle(b,admin()||(!r?has('trip.add'):own(r)&&has('trip.change_own')))});document.querySelectorAll('[onclick^="deleteTrip("]').forEach(b=>{const m=b.getAttribute('onclick')?.match(/deleteTrip\(['\"]?([^'\")]+)/),r=m?.[1]?state.trips.find(x=>String(x.id)===m[1]):null;toggle(b,admin()||!!r&&own(r)&&has('trip.delete_own'))});
  document.querySelectorAll('[onclick="toggleAdd(true)"]').forEach(b=>toggle(b,admin()||has('itinerary.add')));document.querySelectorAll('#recGrid button').forEach(b=>{if((b.textContent||'').includes('加入'))toggle(b,admin()||has('itinerary.add'))});
  for(const b of document.querySelectorAll('[onclick^="editItineraryItem("]')){const id=(b.getAttribute('onclick')||'').match(/\((?:'|")?([^'"\)]+)/)?.[1],r=Object.values(ct?.itinerary||{}).flat().find(x=>String(x.id)===String(id));toggle(b,admin()||!!r&&own(r)&&has('itinerary.change_own'))}for(const b of document.querySelectorAll('[onclick^="delItem("]')){const id=(b.getAttribute('onclick')||'').match(/\((?:'|")?([^'"\)]+)/)?.[1],r=Object.values(ct?.itinerary||{}).flat().find(x=>String(x.id)===String(id));toggle(b,admin()||!!r&&own(r)&&has('itinerary.delete_own'))}
  toggle(document.querySelector('[onclick="addExpense()"]'),admin()||has('expense.add'));toggle(document.querySelector('[onclick="addCheck()"]'),admin()||has('check.add'));toggle(document.querySelector('[onclick="addShop()"]'),admin()||has('shop.add'));
  const memberSec=document.getElementById('tripMemberSection');if(memberSec)toggle(memberSec,admin()||has('trip.change_own')||has('trip.add'));
 }
 window.myTravelApplyPermissionUI=apply;for(const e of ['mytravel-v2-loaded','mytravel-permissions-loaded','mytravel-crud-permission-ready','mytravel-cloud-applied'])window.addEventListener(e,()=>setTimeout(apply,30));const mo=new MutationObserver(()=>requestAnimationFrame(apply));document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>mo.observe(document.body,{childList:true,subtree:true})):mo.observe(document.body,{childList:true,subtree:true});setTimeout(apply,1800);
})();