/* My Travel PWA + authenticated Web Push registration v13 */
(()=>{
  const $=id=>document.getElementById(id),VAPID_PUBLIC_KEY='BDk-gatnAmKJW-X_OaJz2GeZb5FWNOzt0l6Lf-HDpE2cRZakLVkaSVwxAmjwp9TolooDGcUeNDKgx7ud3MsTQSg';let deferredInstallPrompt=null,pushBusy=false;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));const isStandalone=()=>window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true,isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent),platform=()=>isIOS()?'ios':/android/i.test(navigator.userAgent)?'android':/windows/i.test(navigator.userAgent)?'windows':/mac/i.test(navigator.userAgent)?'macos':'web',profile=()=>window.myTravelCurrentProfile?.()||null;
  function key(v){const p='='.repeat((4-v.length%4)%4),raw=atob((v+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
  async function registerSW(){if(!('serviceWorker'in navigator)||!window.isSecureContext)return null;const r=await navigator.serviceWorker.register('./sw.js?v=20',{scope:'./'});r.update().catch(()=>{});return r}async function reg(){return navigator.serviceWorker.ready}async function sub(){try{return await(await reg()).pushManager.getSubscription()}catch(_){return null}}
  async function invoke(action,payload={}){const sb=window.myTravelAuth;if(!sb)throw Error('登入服務尚未就緒');const{data:{session}}=await sb.auth.getSession();if(!session)throw Error('請重新登入');const{data,error}=await sb.functions.invoke('push-subscription',{body:{action,...payload}});if(error)throw error;if(data?.error)throw Error(data.error);return data}async function remote(endpoint){return(await invoke('get',{endpoint})).subscription||null}async function saveSub(s){const j=s.toJSON();return invoke('save',{subscription:{endpoint:s.endpoint,p256dh:j.keys?.p256dh||'',auth:j.keys?.auth||''},device_name:isIOS()?'iPhone / iPad':platform(),platform:platform(),user_agent:navigator.userAgent})}
  async function renderCard(){const more=$('more');if(!more)return;let c=$('pwaInstallCard');if(!c){c=document.createElement('div');c.id='pwaInstallCard';c.className='card';c.style.marginTop='16px';more.prepend(c)}const me=profile(),standalone=isStandalone(),permission='Notification'in window?Notification.permission:'unsupported',s=permission==='granted'?await sub():null;let r=null;if(s&&me)try{r=await remote(s.endpoint)}catch(_){}const bound=!!(s&&r?.user_id&&me?.user_id&&r.user_id===me.user_id&&r.enabled!==false),install=standalone?'<span class="pill">已安裝</span>':deferredInstallPrompt?'<button class="btn" onclick="installMyTravelApp()">安裝 App</button>':isIOS()?'<button class="btn alt" onclick="showIOSInstallHelp()">iPhone 安裝方式</button>':'<span class="muted">可從瀏覽器選單安裝</span>',notify=bound?`<div class="good setting">✅ Push 已綁定：${esc(me.display_name)}</div><button class="btn alt" onclick="syncMyTravelPush()">↻ 驗證並同步</button>`:`<button class="btn" onclick="enableMyTravelPush()">🔔 完成裝置註冊</button>`;c.innerHTML=`<div class="row between"><div><h2>📱 App 與通知</h2><div class="muted">提醒依登入帳號 user_id 發送，不共用裝置身分。</div></div>${install}</div><div class="setting"><b>👤 通知帳號</b><div><b>${me?esc(me.display_name):'尚未登入'}</b></div></div><div class="setting"><b>系統通知</b><div class="muted">${permission==='granted'?(bound?'已開啟並綁定本人':'已允許・待綁定'):'尚未允許'}</div>${me?notify:''}</div>`}
  window.syncMyTravelPush=async()=>{if(pushBusy)return;pushBusy=true;try{const s=await sub(),me=profile();if(!me)throw Error('請重新登入');if(!s)throw Error('尚未建立 Push Subscription');await saveSub(s);alert(`同步成功：${me.display_name}`);await renderCard()}catch(e){alert(e.message)}finally{pushBusy=false}};window.enableMyTravelPush=async()=>{if(pushBusy)return;pushBusy=true;try{const me=profile();if(!me)throw Error('請重新登入');if(isIOS()&&!isStandalone())throw Error('iPhone 必須先加入主畫面');if(await Notification.requestPermission()!=='granted')throw Error('尚未允許通知');const r=await reg();let s=await r.pushManager.getSubscription();if(!s)s=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key(VAPID_PUBLIC_KEY)});await saveSub(s);await renderCard()}catch(e){alert(e.message);await renderCard()}finally{pushBusy=false}};window.installMyTravelApp=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt=null}};window.showIOSInstallHelp=()=>alert('Safari → 分享 → 加入主畫面 → 從 My Travel App 開啟');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;renderCard()});window.addEventListener('mytravel-auth-changed',renderCard);registerSW();setTimeout(renderCard,650);
})();
(()=>{const load=(src,key)=>{if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement('script');s.src=src;s.dataset[key]='1';document.body.appendChild(s)};load('./personal-lists-v1.js?v=4','personalLists');load('./global-travelers-v1.js?v=3','globalTravelers');load('./account-access-v5.js?v=1','accountAccess');load('./v2-data-v1.js?v=3','v2Data');load('./v2-write-v1.js?v=2','v2Write');load('./modal-tools-v1.js?v=1','modalTools');load('./permissions-v1.js?v=1','permissions');load('./booking-owner-v1.js?v=1','bookingOwner');load('./permission-admin-v1.js?v=1','permissionAdmin');load('./crud-permission-guard-v1.js?v=1','crudPermissionGuard');load('./permission-ui-v1.js?v=1','permissionUI')})();