/* My Travel PWA + personal Web Push registration v8 */
(()=>{
  const $=id=>document.getElementById(id);
  const SUPABASE_URL='https://smgtefydmwoqovhldgvp.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY='sb_publishable_GFTHhoVfOHP2edTUSRJa3A_hnevKBeH';
  const VAPID_PUBLIC_KEY='BDk-gatnAmKJW-X_OaJz2GeZb5FWNOzt0l6Lf-HDpE2cRZakLVkaSVwxAmjwp9TolooDGcUeNDKgx7ud3MsTQSg';
  const PERSON_KEY='myTravel_person_name';let deferredInstallPrompt=null,pushBusy=false;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function isStandalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}function platform(){if(isIOS())return'ios';if(/android/i.test(navigator.userAgent))return'android';if(/windows/i.test(navigator.userAgent))return'windows';if(/mac/i.test(navigator.userAgent))return'macos';return'web'}
  function base64UrlToUint8Array(v){const p='='.repeat((4-v.length%4)%4),b=(v+p).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
  function people(){const global=window.myTravelGlobalTravelers?.()||window.state?.people||[];if(global.length)return global.map(p=>p.name);const a=[];for(const t of window.state?.trips||[])for(const p of t.people||[])if(p?.name&&!a.includes(p.name))a.push(p.name);return a}function personName(){return localStorage.getItem(PERSON_KEY)||''}window.myTravelPersonName=personName;
  async function registerSW(){if(!('serviceWorker'in navigator)||!window.isSecureContext)return null;try{const reg=await navigator.serviceWorker.register('./sw.js?v=16',{scope:'./'});reg.update().catch(()=>{});return reg}catch(e){console.warn(e);return null}}async function swRegistration(){return await navigator.serviceWorker.ready}async function getExistingSubscription(){try{return await(await swRegistration()).pushManager.getSubscription()}catch(_){return null}}
  function apiHeaders(prefer='return=minimal'){return{'apikey':SUPABASE_PUBLISHABLE_KEY,'Authorization':`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,'Content-Type':'application/json','Prefer':prefer}}async function readRemoteBinding(endpoint){const res=await fetch(`${SUPABASE_URL}/rest/v1/push_subscriptions?endpoint=eq.${encodeURIComponent(endpoint)}&select=id,person_name,enabled,platform,last_seen_at`,{headers:apiHeaders()});if(!res.ok)throw new Error(`讀取裝置綁定失敗 (${res.status})`);return(await res.json())[0]||null}
  async function saveSubscription(sub,whoOverride){const who=whoOverride||personName();if(!who)throw new Error('請先選擇「這台裝置是誰」');const json=sub.toJSON(),row={endpoint:sub.endpoint,p256dh:json.keys?.p256dh||'',auth:json.keys?.auth||'',device_name:isIOS()?'iPhone / iPad':platform(),platform:platform(),user_agent:navigator.userAgent,person_name:who,enabled:true,last_seen_at:new Date().toISOString()};let res=await fetch(`${SUPABASE_URL}/rest/v1/push_subscriptions?endpoint=eq.${encodeURIComponent(sub.endpoint)}`,{method:'PATCH',headers:apiHeaders('return=representation'),body:JSON.stringify(row)});if(!res.ok)throw new Error(`更新裝置身分失敗 (${res.status})`);let rows=await res.json();if(!rows.length){res=await fetch(`${SUPABASE_URL}/rest/v1/push_subscriptions`,{method:'POST',headers:apiHeaders('return=representation'),body:JSON.stringify(row)});if(!res.ok)throw new Error(`建立 Push Subscription 失敗 (${res.status})`)}const verify=await readRemoteBinding(sub.endpoint);if(!verify||verify.person_name!==who)throw new Error(`裝置身分驗證失敗：雲端目前是「${verify?.person_name||'未設定'}」`);return verify}
  window.setMyTravelPerson=async function(name){if(!name||pushBusy)return;const old=personName();pushBusy=true;try{const sub=await getExistingSubscription();if(!sub)throw new Error('這台裝置尚未建立 Push Subscription，請先完成裝置註冊');await saveSubscription(sub,name);localStorage.setItem(PERSON_KEY,name);window.dispatchEvent(new CustomEvent('mytravel-person-changed',{detail:{name}}));await renderCard();alert(`裝置身分已切換為「${name}」`)}catch(e){old?localStorage.setItem(PERSON_KEY,old):localStorage.removeItem(PERSON_KEY);await renderCard();alert(e?.message||String(e))}finally{pushBusy=false}};
  async function renderCard(){const more=$('more');if(!more)return;let card=$('pwaInstallCard');if(!card){card=document.createElement('div');card.id='pwaInstallCard';card.className='card';card.style.marginTop='16px';more.prepend(card)}const standalone=isStandalone(),permission=('Notification'in window)?Notification.permission:'unsupported',sub=permission==='granted'?await getExistingSubscription():null,ps=people();let who=personName(),remote=null;if(sub)try{remote=await readRemoteBinding(sub.endpoint);if(remote?.person_name&&remote.person_name!==who){who=remote.person_name;localStorage.setItem(PERSON_KEY,who)}}catch(e){}let action=standalone?'<span class="pill">已安裝</span>':deferredInstallPrompt?'<button class="btn" onclick="installMyTravelApp()">安裝 App</button>':isIOS()?'<button class="btn alt" onclick="showIOSInstallHelp()">iPhone 安裝方式</button>':'<span class="muted">可從瀏覽器選單安裝／加入主畫面</span>';let notifyAction=permission==='granted'&&sub?`<div class="good setting" style="margin-top:10px">✅ Push 已綁定${remote?.person_name?`：${esc(remote.person_name)}`:''}</div><button class="btn alt" style="margin-top:10px" onclick="syncMyTravelPush()">↻ 驗證並同步</button>`:'<button class="btn" style="margin-top:10px" onclick="enableMyTravelPush()">🔔 完成裝置註冊</button>';const opts=ps.length?ps.map(n=>`<option value="${esc(n)}" ${n===who?'selected':''}>${esc(n)}</option>`).join(''):'<option value="">請先新增全域旅伴</option>';card.innerHTML=`<div class="row between"><div><h2>📱 App 與通知</h2><div class="muted">每台裝置綁定一位旅伴，只接收自己的行前提醒。</div></div>${action}</div><div class="setting"><b>👤 這台裝置是誰</b><select style="margin-top:7px" onchange="setMyTravelPerson(this.value)"><option value="">請選擇</option>${opts}</select><div class="muted">選項來自全域旅伴名單。</div></div><div class="grid g2" style="margin-top:12px"><div class="setting"><b>App 模式</b><div class="muted">${standalone?'✅ 已使用獨立 App 模式':'瀏覽器模式'}</div></div><div class="setting"><b>系統通知</b><div class="muted">${permission==='granted'?(sub?`已開啟・${remote?.person_name||who||'尚未綁定'}`:'已允許・尚未註冊'):permission==='denied'?'已拒絕':'尚未允許'}</div>${notifyAction}</div></div>`}
  window.syncMyTravelPush=async function(){if(pushBusy)return;pushBusy=true;try{const sub=await getExistingSubscription(),who=personName();if(!sub||!who)throw new Error('請先完成裝置註冊與身分選擇');const v=await saveSubscription(sub,who);alert(`同步成功：這台裝置 = ${v.person_name}`);await renderCard()}catch(e){alert(e?.message||String(e))}finally{pushBusy=false}};window.enableMyTravelPush=async function(){if(pushBusy)return;pushBusy=true;try{if(!personName())throw new Error('請先選擇「這台裝置是誰」');if(isIOS()&&!isStandalone())throw new Error('iPhone 必須先加入主畫面');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('尚未允許通知');const reg=await swRegistration();let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64UrlToUint8Array(VAPID_PUBLIC_KEY)});await saveSubscription(sub,personName());await renderCard()}catch(e){alert(e?.message||String(e));await renderCard()}finally{pushBusy=false}};
  window.installMyTravelApp=async function(){if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();deferredInstallPrompt=null};window.showIOSInstallHelp=()=>alert('Safari → 分享 → 加入主畫面 → 從 My Travel App 開啟');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;renderCard()});window.addEventListener('mytravel-travelers-updated',()=>renderCard());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')renderCard()});window.addEventListener('focus',renderCard);registerSW();const start=()=>setTimeout(renderCard,650);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
})();
(()=>{if(!document.querySelector('script[data-personal-lists]')){const s=document.createElement('script');s.src='./personal-lists-v1.js?v=2';s.dataset.personalLists='1';document.body.appendChild(s)}if(!document.querySelector('script[data-global-travelers]')){const s=document.createElement('script');s.src='./global-travelers-v1.js?v=1';s.dataset.globalTravelers='1';document.body.appendChild(s)}})();